### ISSUE TITLE
Curator deletes complete days

### ISSUE THREAD

**Issue by diegolopmon** [elastic/curator#1004]
I don't know if it's a feature or a bug, but if I run the following action:
```
actions:
  1:
    action: delete_indices
    description: >-
      Delete docker-filebeat-* indices
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: docker-filebeat-*
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: hours
      unit_count: 24
      exclude:
```
When the oldest log entry reach 24h limit, all log entries of its day are deleted, from 00:00 to 23:59. Even the log entries newest than 24h.
