### ISSUE TITLE
Documentation for number_of_replicas during restore action is incorrect

### ISSUE THREAD

**Issue by Strijd** [elastic/curator#1015]
curator version = 5.1
elasticsearch = 5.4.0 

Summary:
Enforcing number of replicas per shard during restore action, doesn't seem to work 

```
extra_settings:
        settings:
          number_of_shards: 1
          number_of_replicas: 0
```
After checking  index settings, I see number of replicas is set to "1" -- looks like its a default
