### ISSUE TITLE
[FEATURE] Add strftime interpolation to migration prefix/suffix

### ISSUE THREAD

**Issue by sergii-rolskii** [elastic/curator#1055]
Hi guys,
I need to reindex index '.kibana' (NOT SNAPSHOT) everyday to index '.kibana-2017-09-13' (%Y-%m-%d)
In the future, I plan to delete index older 5 days.

my config:
```
actions:
  1:
    action: reindex
    description: reindex .kibana to .kibana-Y-m-d
    options:
      ignore_empty_list: True
      wait_interval: 9
      max_wait: -1
      migration_suffix: -"%Y-%m-%d"
      request_body:
        source:
          index: '.kibana'
        dest:
          index: MIGRATION
    filters:
    - filtertype: none
```
but I have error:

```
2017-09-13 12:33:14,215 ERROR     The index described as ".kibana-"%Y-%m-%d"" was not found after the reindex operation. Check Elasticsearch logs for more information.
2017-09-13 12:33:14,216 ERROR     Failed to complete action: reindex.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: Reindex failed. The index or alias identified by ".kibana-"%Y-%m-%d"" was not found.
```

If I set **migration_suffix: -backup** (example) It's work fine
How can I get the correct index name in the format '.kibana-2017-09-13'?

**Comment by untergeek** [comment]
There is (currently) no interpretation of strftime strings in the `migration_prefix` or `migration_suffix`.  At present—even if this functionality were added—this would only yield the current day/month/year.  This can be a feature request for now.

**Comment by untergeek** [comment]
You don't need the `MIGRATION` feature for this.  Date math already works:

```
actions:
  1:
    action: reindex
    description: reindex .kibana to .kibana-Y-m-d
    options:
      ignore_empty_list: True
      wait_interval: 9
      max_wait: -1
      request_body:
        source:
          index: '.kibana'
        dest:
          index: '<.kibana-{now-1d/d}>'
    filters:
    - filtertype: none
```
