### ISSUE TITLE
Feature request: allow filtering nodes by attribute for shrink action

### ISSUE THREAD

**Issue by dandrestor** [elastic/curator#1087]
The title pretty much says it all. It would be nice to be able to do something like:

```
action: shrink
  node_filters:
    exclude_attribute:
      attribute: box_type
      value: hot
```

May also apply to other actions also.
