### ISSUE TITLE
Delete templates without an index

### ISSUE THREAD

**Issue by ruflin** [elastic/curator#1100]
Each Beat generates a template for each version of the Beat to make sure each event sent by a Beat gets the right template applied. Beats are updated over time and old indices can be cleaned up by curator. But the old templates stay around. Right now they have to be manually deleted.

It would be great to have a feature in curator that deletes all templates for which no index exists. As Beats creates a template when the first event is sent, it would mean that for all the templates that exist without an index, the indices for it were deleted and not beats send data anymore. 

There could be edge cases where a beat did not send for a longer time but I think this is more an edge case.

Config wise I'm thinking of something like:

```
actions:
  1:
    action: delete_templates
    description: >-
      Delete unused templates tempalte
    options:
      delete_templates_without_index: True
```
