### ISSUE TITLE
Action allocation does not apply correctly to all indices

### ISSUE THREAD

**Issue by allansene** [elastic/curator#1108]
Guys,

I'm using curator `elasticsearch-curator-5.4.0-1.x86_64` with `elasticsearch-5.5.0` on EC2 machines. **Sometimes**, when I try an allocation action, Curator does not send all shards to my warmers nodes. It is arbitrarily adding some `_name` property inside **a random** index settings. All `heartbeat-*` logs are fine, but one. :(

Look:

<img width="828" alt="captura de tela 2017-11-27 as 19 49 14" src="https://user-images.githubusercontent.com/6767685/33291320-9277b3ec-d3ac-11e7-9c28-ccd0e941886f.png">

``` json
{
  "heartbeat-2017.11.23": {
    "settings": {
      "index": {
        "routing": {
          "allocation": {
            "require": {
              "_name": "mm-prd-elasticsearch-dados-warm-08",
              "box_type": "warm"
            }
          }
        },
        "mapping": {
          "total_fields": {
            "limit": "10000"
          }
        },
        "refresh_interval": "5s",
        "number_of_shards": "6",
        "blocks": {
          "write": "false"
        },
        "provided_name": "heartbeat-2017.11.23",
        "creation_date": "1511395209570",
        "unassigned": {
          "node_left": {
            "delayed_timeout": "5m"
          }
        },
        "number_of_replicas": "1",
        "uuid": "NjqtwFw7QF-06e85AtItrA",
        "version": {
          "created": "5050099"
        }
      }
    }
  }
}
```
My conf is:
``` yml
---
actions:
  1:
    action: allocation
    description: >-
      Apply shard allocation routing to 'require' 'tag=warm' for hot/warm node
      setup for logs- indices older than 2 days, based on index_creation
      date
    options:
      key: box_type
      value: warm
      allocation_type: require
      wait_for_completion: true
      timeout_override:
      continue_if_exception: false
      disable_action: false
    filters:
    - filtertype: pattern
      kind: regex
      value: '.*beat.*'
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 2
```
