### ISSUE TITLE
[FEATURE] Add alias option to Shrink action to allow aliasing original index name to newly created index after deletion of original index

### ISSUE THREAD

**Issue by geekpete** [elastic/curator#1126]
The Shrink action provides a great way to process a batch of indices, shrink them to new indices and delete the originals.

It would be super handy to also have the option to add the alias for the original index name to the newly created shrunken index for each index processed.

Currently you have to either:

- Leave a bunch of duplicate indices around until the end of the batch then delete+alias, putting unnecessary pressure on resources depending on the size of the indices/batch...or
- run with missing indices until the end of the batch then add the aliases at the end of the batch

And with the alias+delete steps, these are also not atomic and it would be neater if Curator's Alias action also had the option to use the `remove_index` action provided by the Index Alias API:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#CO146-3

**Comment by geekpete** [comment]
The delete+alias option could also be interesting for the reindex action using migration mode, but would have more risks involved compared to shrink where the mapping is guaranteed to be the same.

**Comment by andrassy** [comment]
+1

**Comment by efazenda** [comment]
+1

**Comment by dguendisch** [comment]
Currently also struggling with curator's `alias` action not having the `remove_index` option of elasticsearch's alias action to swap an index `test` with an alias `test` pointing to some other index.
Makes it hard to do a bullet-proof migration of data ...

**Comment by kmickeletto** [comment]
+1 on this as well.  Kind of a disappointment that the functionality isn't built into Curator already.

**Comment by singerxt** [comment]
Hello!

This is a workaround for this problem. However, this is not a 0 downtime process and requires configured snapshots.

```
actions:
  '1':
    action: shrink
    description: 'Shrink all indexes to 1 shard. All original indexes will be deleted!'
    options:
      disable_action: false
      ignore_empty_list: true
      shrink_node: DETERMINISTIC
      node_filters:
        permit_masters: false
        exclude_nodes:
          - not_this_node
      number_of_shards: 1
      number_of_replicas: 1
      shrink_prefix: null
      shrink_suffix: '-shrinked'
      copy_aliases: true
      delete_after: true
      wait_for_active_shards: 1
      extra_settings:
        settings:
          index.codec: best_compression
          index.mapping.total_fields.limit: 10000
      wait_for_completion: true
      wait_for_rebalance: true
      wait_interval: 9
      max_wait: -1
    filters:
      -
        filtertype: pattern
        kind: regex
        value: kibana
        exclude: true
  '2':
    action: snapshot
    options:
      repository: repo-ue1-1-prod0-content-legacy2
      name: null
      ignore_unavailable: false
      include_global_state: true
      partial: false
      wait_for_completion: true
      skip_repo_fs_check: false
      timeout_override: null
      continue_if_exception: false
      disable_action: false
    filters:
        -
          filtertype: pattern
          kind: regex
          value: kibana
          exclude: true
  '3':
    action: delete_indices
    options:
      ignore_empty_list: true
      timeout_override: null
      continue_if_exception: true
      disable_action: false
    filters:
      -
        filtertype: pattern
        kind: regex
        value: kibana
        exclude: true
  '4':
    action: restore
    description: 'Restore all indexes and remove shrink suffix from index name'
    options:
      repository: repo-ue1-1-prod0-content-legacy2
      name: null
      indices: null
      include_aliases: True
      rename_pattern: (.+)-shrinked
      rename_replacement: $1
      wait_for_completion: true
      wait_interval: 10
    filters:
      -
        filtertype: none
```
