### ISSUE TITLE
delete_indexes with filtertype age/field_stats throws exception on indexes without any documents

### ISSUE THREAD

**Issue by quintonm** [elastic/curator#1130]
Example config:

```
actions:
  1:
    action: delete_indices
    description: Delete log-message-* indices older than 7 days
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: log-message-
    - filtertype: age
      source: field_stats
      direction: older
      field: 'timestamp'
      stats_result: max_value
      unit: days
      unit_count: 7

```
### Expected Behavior
the age filter type should exclude indexes that have no documents when the the source is file_stats

### Actual Behavior
An exception is thrown.

```
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,156 DEBUG          curator.indexlist          filter_by_age:431  Filtering indices by age
-- | --
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,156 DEBUG          curator.indexlist _get_field_stats_dates:247  Getting index date by querying indices for min & max value of timestamp field
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,156 DEBUG          curator.indexlist _get_field_stats_dates:250  Cannot use query closed indices. Omitting any closed indices.
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,156 DEBUG          curator.indexlist          filter_closed:658  Filtering closed indices
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,156 DEBUG          curator.indexlist       empty_list_check:184  Checking for empty list
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,156 DEBUG          curator.indexlist           working_list:195  Generating working list of indices
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,157 DEBUG          curator.indexlist          filter_closed:663  Index log-message-2018-01-10 state: open
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,157 DEBUG          curator.indexlist           __actionable:36   Index log-message-2018-01-10 is actionable and remains in the list.
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,157 DEBUG          curator.indexlist          filter_closed:663  Index log-message-active-1 state: open
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,157 DEBUG          curator.indexlist           __actionable:36   Index log-message-active-1 is actionable and remains in the list.
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,255 DEBUG          curator.indexlist _get_field_stats_dates:263  RESPONSE: {u'hits': {u'hits': [], u'total': 798000, u'max_score': 0.0}, u'_shards': {u'successful': 5, u'failed': 0, u'skipped': 0, u'total': 5}, u'took': 5, u'aggregations': {u'max': {u'value_as_string': u'2018-01-10T17:36:54.853Z', u'value': 1515605814853.0}, u'min': {u'value_as_string': u'2018-01-10T00:12:13.288Z', u'value': 1515543133288.0}}, u'timed_out': False}
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,255 DEBUG          curator.indexlist _get_field_stats_dates:267  r: {u'max': {u'value_as_string': u'2018-01-10T17:36:54.853Z', u'value': 1515605814853.0}, u'min': {u'value_as_string': u'2018-01-10T00:12:13.288Z', u'value': 1515543133288.0}}
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,255 DEBUG          curator.indexlist _get_field_stats_dates:271  s: {'max_value': 1515605814, 'min_value': 1515543133, 'creation_date': 1515698279}
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,352 DEBUG          curator.indexlist _get_field_stats_dates:263  RESPONSE: {u'hits': {u'hits': [], u'total': 0, u'max_score': 0.0}, u'_shards': {u'successful': 5, u'failed': 0, u'skipped': 0, u'total': 5}, u'took': 2, u'aggregations': {u'max': {u'value': None}, u'min': {u'value': None}}, u'timed_out': False}
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,352 DEBUG          curator.indexlist _get_field_stats_dates:267  r: {u'max': {u'value': None}, u'min': {u'value': None}}
11-Jan-2018 22:32:42 | 2018-01-11 22:32:42,353 ERROR                curator.cli                    run:184  Failed to complete action: delete_indices.  <type 'exceptions.TypeError'>: int() argument must be a string or a number, not 'NoneType'

```

### Steps to Reproduce the Problem
PUT /log-message-1

execute curator with the config listed above

### Specifications

  - Version: 5.4.1
  - Platform: linux
