### ISSUE TITLE
Long running snapshot deletion fails with `snapshot_missing_exception`

### ISSUE THREAD

**Issue by JD557** [elastic/curator#1134]
If a snapshot takes more than one minute to delete, it fails with a u'snapshot_missing_exception':

**Log:**
```
2018-01-22 09:15:26,047 INFO      Deleting snapshot hourly-2018-01-15-07...
2018-01-22 09:16:26,000 ERROR     Failed to complete action: delete_snapshots.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: TransportError(404, u'snapshot_missing_exception', u'[s3:hourly-2018-01-15-07] is missing')
```

I can delete the snapshots manually without a problem, so I don't think that the problem is on the server side.

I think that the snapshot deletion starts, is retried internally (probably via the [elasticsearch python client internal retry logic](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L320-L335)), and the retry fails (because the snapshot is removed from the list while its being deleted).

## Specifications

  - Version: ES 5.6.4 / Curator 5.4.0
  - Platform: Ubuntu (AWS)

## Action

```
    action: delete_snapshots
    description: Delete old snapshots
    options:
      repository: s3
      timeout_override: 1200
      continue_if_exception: True
      ignore_empty_list: True
    filters: <redacted>
```
