### ISSUE TITLE
[FEATURE] Add ability to filter/rollover aliases using regex (similar to filtertype: pattern)

### ISSUE THREAD

**Issue by lruslan** [elastic/curator#1141]
In our cluster we have around 10-20 indexes which use rollover feature and orchestrated by curator.
We also use aliases to tag inactive(rolled) indexes.
To target inactive indexes I use "action: alias"  and select all indexes except active write index.
Without ability to use regexp to filter aliases I have to edit curator action file every time new index added, only to add new index name.
If I could use filter to select aliases with prefix based pattern I'd be able to use one action file to manage all indexes. And all new indexes that follow naming convention (start with prefix) would be automatically picked up by curator.

Maybe it's possible:
- extend 'filtertype: pattern' to support aliases as well (just use parameter to enable "alias mode"), then we could use pattern instead of 'filtertype: alias'
- extend 'action: rollover' to support filters - so filter would return list of alias names where rollover has to be applied

Example of action file:
 ```
 1:
    action: rollover
    description: >-
      Rollover all active indexes where alias matches regexp(prefix) 'write_*'
    options:
      # select active index (all aliases that begin with "write_")
      # use prefix/regex instead of full name 
      name: write_
      conditions:
        max_docs: 40000000
  2:
    action: alias
    description: >-
      Set alias 'rolled' on rolled inactive indexes
    options:
      ignore_empty_list: True
      continue_if_exception: False
      disable_action: False
      name: rolled
    add:
      filters:
      - filtertype: pattern
        kind: prefix
        value: myindex-
      - filtertype: alias
        # exclude active write index , all aliases that begin with "write_"
        # use prefix/regex instead of full name
        aliases: write_
        exclude: True

```
