### ISSUE TITLE
Curator aren't showing Elastic indexes.

### ISSUE THREAD

**Issue by Krieffer** [elastic/curator#1150]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

### Expected Behavior

Curator gets the Kibana's/Elasticsearch's indexes.

### Actual Behavior

Curator doesn't get those indexes.

### Steps to Reproduce the Problem

  1. Executing any command in DEBUG mode.

### Specifications

  - Version: 5.4
  - Platform: Linux
  - Subsystem: Ubuntu

## Context (Environment)

With this issue, I can't delete indexes because Curator can't find them.

## Detailed Description

I'm trying to manipulate both Kibana and Elastic indexes with the Curator, but in the DEBUG mode, those indexes isn't showing.

**Comment by untergeek** [comment]
What command are you executing?  What does your config.yml file look like (don't share passwords).

e.g.
```
---
client:
  hosts: [ "127.0.0.1" ]
  port: 9200

logging:
  loglevel: DEBUG
  logfile: "/var/log/curator/curator.log"
```

You don't technically need more than this.  You don't even need `logfile`.  Without it, Curator will log to stdout.  Is this file properly indented?

Or, are you using `curator_cli`?  If so, what command?
```
curator_cli --host 127.0.0.1 --port 9200 show_indices --verbose --header
```
This should show all of your indices on the command-line.

**Comment by Krieffer** [comment]
So, I'm using the "DEBUG" to show the logs that Curator is "seeing". And it's has only two ['myindex', 'megacorp'].

I'm running the "delete_indices.yml" command.

My config file (those numbers are fictional):

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - 127.0.0.1
  port: 9200

logging:
  loglevel: DEBUG
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```

**Comment by untergeek** [comment]
What does your `delete_indices.yml` look like?

**Comment by Krieffer** [comment]
```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 1 minute (based on index name), for any
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: elastalert
      exclude: False
    - filtertype: age
      source: creation_date
      direction: older
      unit: minutes
      unit_count: 1


```
