### ISSUE TITLE
Alias by date

### ISSUE THREAD

**Issue by duylong** [elastic/curator#1169]
Hi,

I would like to automatically generate aliases based on the date of the index (logstash-2018.03.12 => my-alias-2018.03.12). I did not see in the documentation the functionality, I searched badly?

Best regards,

**Comment by untergeek** [comment]
There is a feature coming in the 5.5 release which will help you to get an acceptable result, hopefully, using Elasticsearch date math.  See the _pending_ documentation [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.x/option_name.html#_date_math_2).

**Comment by untergeek** [comment]
Date math is an Elasticsearch concept.  Rather than extract the date from the index (which would be a regular expression operation), date math would allow you to do a relative match of the date.

For example, if I ran Curator at 02:00 UTC, today's index might be `logstash-2018.03.19`, but I want to associate _yesterday's_ index with an alias.  I can use the index selection filters to select only yesterday's index, but would use date math to get the alias name to match:

```
actions:
  1:
    action: alias
    description: Associate my-alias-%Y.%m.%d with yesterday's logstash-%Y.%m.%d index with matching dates
    options:
      name: "<my_alias-{now/d-1d}>"
    add:
      filters:
      - filtertype: pattern
        kind: prefix 
        value: logstash-
      - filtertype: period
        source: name
        range_from: -1
        range_to: -1
        timestring: '%Y.%m.%d'
        unit: days
```

This example action file should only match yesterday's `logstash-%Y.%m.%d` index because of the `pattern` and `period` filters, and the date math in the `name` will create a `my_alias-%Y.%m.%d` alias associated with that index.
