### ISSUE TITLE
Reindex failed. Error - The index or alias identified by <dest_index> was not found

### ISSUE THREAD

**Issue by erdarun** [elastic/curator#1170]
### Expected Behavior
Reindex operation should have been successfully completed

### Actual Behavior

Reindex failed. The index or alias identified by <dest_index> was not found

### Steps to Reproduce the Problem
**curator-reindex script**
_actions:  
  1:  
    description: "Reindex index1 into index2"
    action: reindex
    options:
      disable_action: False
      wait_interval: 9
      max_wait: -1
      request_body:
        source:
          index: test-events
        dest:
          index: reindex_test-events
    filters:
    - filtertype:_ 

**Curator Logs**
2018-03-15 14:38:12,821 INFO      Preparing Action ID: 1, "reindex"
2018-03-15 14:38:12,828 INFO      Trying Action ID: 1, "reindex": Reindex index1 into index2
2018-03-15 14:38:12,845 INFO      Commencing reindex operation
2018-03-15 14:38:12,851 INFO      Task "reindex from [test-events] to [reindex_test-events]" with task_id "7aroLMAqTeyG6u-_f7N_cQ:45155" has been running for 0.003328736 seconds
2018-03-15 14:38:21,868 INFO      Task "reindex from [test-events] to [reindex_test-events]" completed at 2018-03-15T14:38:12Z.
2018-03-15 14:38:21,871 ERROR     The index described as "reindex_test-events" was not found after the reindex operation. Check Elasticsearch logs for more information.
2018-03-15 14:38:21,871 ERROR     Failed to complete action: reindex.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: Reindex failed. The index or alias identified by "reindex_test-events" was not found.

### Specifications

  - Version:5.4.1/5.4.0
  - Platform: ElasticSearch 6.2

## Context (Environment)
We can't do reindexing of restored index.

**Comment by untergeek** [comment]
Is dynamic index creation disabled? If Elasticsearch is unable to create the index automatically, that would be the result.

Otherwise, please enable debug logging and attach the relevant logs.  What you are describing does not happen in the Curator CI tests that perform both local and remote reindexing tests, and I'd like to better understand what's happening in your environment.

**Comment by erdarun** [comment]
Reindex failed due to source index name mentioned was index alias name. After mentioning explicit source index name instead of alias it worked.

I have query like after reindex operation source index will exist or not? 
Because as per our testing source index still exists along with destination index.

**Comment by untergeek** [comment]
The source index will not be deleted automatically after a reindex operation, neither by Elasticsearch, nor Curator.

**Comment by afharo** [comment]
I'm suffering from the same issue and found the reason: it is a _queried_ reindex for a rotated index. I have this action:
```YAML
    action: reindex
    description: >-
      Copy GreenMile logs into it's own indexes (in the form of INDEX-YYYY.MM.DD-GreenMile so we don't lose them)
    options:
      disable_action: ${GREENMILE_COPY_DISABLED:False} # Enabled by default
      continue_if_exception: False
      wait_for_completion: True
      max_wait: -1
      wait_interval: 10
      timeout: 300 # seconds before timeout
      migration_suffix: -GreenMile
      request_body:
        source:
          index: REINDEX_SELECTION # Keyword that will use the index names obtained from the filters
          query:
            - prefix:
                workflowName: 'GreenMile'
            bool:
              should:
                - prefix:
                    workflowName: 'GreenMile'
                - has_parent:
                    parent_type: 'jobs'
                    query:
                      prefix:
                        workflowName: 'GreenMile'
        dest:
          index: MIGRATION # Keyword that will use the same name as the original index name (plus the migration_suffix)
          version_type: 'external'
    filters:
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: ${OLDLOGS_DELETION_DAYS_COUNT:30}
      # Exclude previously existing *-GreenMile indexes
      - filtertype: pattern
        kind: suffix
        value: -GreenMile
        exclude: True
```
The idea is to move certain documents to another "archive" index so we can rotate the rest indexes.

In my test, I only have documents in `INDEX-2019.03.08` but curator is failing on `INDEX-2019.03.18` where there are no documents to be copied.

Curator should skip the existance of the target if there are no processed results from the query (total === 0):
```
2019-05-09 15:38:31,817 DEBUG              curator.utils             task_check:1650 TASK_DATA: {u'completed': True, u'task': {u'node': u'0wCjrAIlRJ23tOpxD_FSLg', u'status': {u'retries': {u'bulk': 0, u'search': 0}, u'updated': 0, u'batches': 0, u'throttled_until_millis': 0, u'throttled_millis': 0, u'noops': 0, u'created': 0, u'deleted': 0, u'requests_per_second': -1.0, u'version_conflicts': 0, u'total': 0}, u'description': u'reindex from [appc-jobs-2019.03.18] to [appc-jobs-2019.03.18-GreenMile]', u'running_time_in_nanos': 5440982, u'cancellable': True, u'action': u'indices:data/write/reindex', u'type': u'transport', u'id': 2352433, u'start_time_in_millis': 1557416311787}, u'response': {u'retries': {u'bulk': 0, u'search': 0}, u'updated': 0, u'batches': 0, u'throttled_until_millis': 0, u'throttled_millis': 0, u'noops': 0, u'created': 0, u'deleted': 0, u'took': 5, u'requests_per_second': -1.0, u'timed_out': False, u'failures': [], u'version_conflicts': 0, u'total': 0}}
```
