### ISSUE TITLE
Curator fails to delete index when multiple ES hosts are configured

### ISSUE THREAD

**Issue by guitmz** [elastic/curator#1190]
My `curator.yaml` config file contains the following:

```yaml
---
client:
  hosts:
    - http://elasticsearch-1
    - http://elasticsearch-2
    - http://elasticsearch-3
  port: 80
  use_ssl: False
  ssl_no_validate: False
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```

When I run using this configuration, it fails with the following:

```
2018-03-29 10:07:43,359 INFO      curator.actions.delete_indices           __chunk_loop:502  ---deleting index elasticsearch-3-2018.03.19

2018-03-29 10:07:43,389 ERROR                curator.cli                    run:184  Failed to complete action: delete_indices.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: TransportError(404, 'index_not_found_exception', 'no such index')
```

I have checked `elasticsearch-3` host and the index `elasticsearch-3-2018.03.19` is indeed still present there (curator couldn't delete it, neither the other ones that it was supposed to delete).

However, if I change my `curator.yaml` and remove `elasticsearch-1` and `elasticsearch-2` hosts, it runs successfully.

```
2018-03-29 10:11:19,059 INFO      curator.actions.delete_indices           __chunk_loop:502  ---deleting index elasticsearch-3-2018.03.19
2018-03-29 10:11:19,578 DEBUG              curator.utils            get_indices:644  Detected Elasticsearch version 5.6.5
2018-03-29 10:11:19,578 DEBUG     curator.actions.delete_indices         _verify_result:489  Successfully deleted all indices on try #1
```
It might be the case where its trying to look for `elasticsearch-3-2018.03.19` in the incorrect ES host but I'm not sure (i.e. trying to find a index from `elasticsearch-3` inside of `elasticsearch-2` host).

### Expected Behavior
Curator deletes all indexes based on my `actions.yaml` pattern on all hosts inside the `hosts:` key of my `curator.yaml` configuration file.

### Actual Behavior
Curator starts with the latest host of my configuration file and fails when trying to delete the oldest index (based on my retention period configuration).

### Steps to Reproduce the Problem
  1. Create a curator config file with 2 or more Elasticsearch hosts
  2. Run curator trying to delete some indexes

### Specifications
Linux, tested on different distros, including inside Docker.
Elasticsearch version 5.6.5
Curator 5.5.1

Thanks!
