### ISSUE TITLE
Getting 'No "add" or "remove" operations' when ignore_empty_list is True

### ISSUE THREAD

**Issue by ondrejchmelar** [elastic/curator#1209]
### Expected Behavior

Curator action ends with success when `ignore_empty_list: True` and no aliases are to be added/removed.

### Actual Behavior

Curator fails with 
```
ERROR     Failed to complete action: alias.  <class 'curator.exceptions.ActionError'>: No "add" or "remove" operations
```
at https://github.com/elastic/curator/blob/v5.4.1/curator/actions.py#L116

### Steps to Reproduce the Problem

actions/add-alias.yml:
```
---
actions:
  remove1:
    action: alias
    description: "Remove indices to be closed from aliases."
    options:
      ignore_empty_list: True
      name: logstash-app.xxx
    remove:
      filters:
        - filtertype: pattern
          kind: prefix
          value: "logstash-app.yyy-"
        - filtertype: age
          source: name
          timestring: '%Y-%m'
          direction: older
          unit: days
          unit_count: 31
```
### Specifications

  - Version: elasticsearch-curator-v5.4.1
  - Platform: linux
  - Subsystem: ubuntu

## Context (Environment)

https://discuss.elastic.co/t/curator-alias-add-not-working-if-remove-list-is-empty/73549

## Detailed Description

I ran into this issue (https://discuss.elastic.co/t/curator-alias-add-not-working-if-remove-list-is-empty/73549) with managing aliases and solved it by separating add and remove to independent actions

Now I'm getting "No "add" or "remove" operations" on a remove operation even though ignore_empty_list: True

Quick debug in the curator code shows the action is not properly ignoring empty list of aliases to create and remove.
https://github.com/elastic/curator/blob/v5.4.1/curator/actions.py#L116

Will send an illustrative PR soon.

**Comment by ondrejchmelar** [comment]
https://github.com/elastic/curator/pull/1210

**Comment by untergeek** [comment]
You seem to have missed [this option](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/option_warn_if_no_indices.html) for the current version of Curator which addresses the issue.

**Comment by ondrejchmelar** [comment]
I missed it in the docs but you can see from the code that it has no effect in this usecase. 
warn_if_no_indices comes into effect when empty_list_check fails. For me it doesn't raise an exception - the problem begins a couple of rows later when `if index in aliases` is false and nothing gets pushed in self.actions.

2018-05-04 09:55:33,092 INFO      Preparing Action ID: remove1, "alias"
2018-05-04 09:55:52,065 WARNING   No indices found after processing filters. Nothing to remove from logstash-app.xxx-yyy
2018-05-04 09:55:52,065 INFO      Updating aliases...
2018-05-04 09:55:52,065 ERROR     Failed to complete action: alias.  <class 'curator.exceptions.ActionError'>: No "add" or "remove" operations

```
---
actions:

  remove1:
    action: alias
    description: "Remove indices to be closed from aliases."
    options:
      ignore_empty_list: True
      warn_if_no_indices: True
      name: logstash-app.xxx-yyy
    remove:
      filters:
        - filtertype: pattern
          kind: prefix
          value: "logstash-app.yyy-"
        - filtertype: age
          source: name
          timestring: '%Y-%m-%d'
          direction: older
          unit: days
          unit_count: 16
```
