### ISSUE TITLE
Resolve date math in dry run output

### ISSUE THREAD

**Issue by bczifra** [elastic/curator#1239]
### Expected Behavior
When using date math for index names in dry run mode, the dry run output should render the index name with the date math applied.

### Actual Behavior
The logs include an "is using Elasticsearch date math" line:
```
2018-06-25 14:44:31,950 INFO               curator.utils     parse_date_pattern:1338 "<logstash-{now/d+1d}>" is using Elasticsearch date math.
```
and then display the "fully rendered name" as:
```
2018-06-25 14:44:31,951 DEBUG              curator.utils     parse_date_pattern:1349 Fully rendered name: <logstash-{now/d+1d}>
```

### Steps to Reproduce the Problem
```
actions:
  1:
    action: create_index
    description: >-
      Create index without shard replication for faster reindexing
    options:
      name: '<logstash-{now/d+1d}>'
      extra_settings:
        settings:
          number_of_shards: 1
          number_of_replicas: 0
      continue_if_exception: False
```

### Specifications

  - Version: 5.5

## Context (Environment)
It is difficult to verify that the provided date math is correct and valid because the dry run logging doesn't indicate what the final index name would be based on the date math.

## Detailed Description
Please render the full index name, including the applied date math, in the dry run logs.
