### ISSUE TITLE
Array/List Environment variables not supported

### ISSUE THREAD

**Issue by bschneiders** [elastic/curator#1247]
The [current documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.x/option_request_body.html#option_request_body) says you can specify an index list like this:

```
  request_body:
    source:
      index: ['index1', 'index2', 'index3']
    dest:
      index: new_index
```
In reality, that syntax will result in ES API errors such as:

```
"description":"reindex from ['index1'] to [index1_r]","start_time_in_millis":1532101508423,"running_time_in_nanos":103798,"cancellable":true},"error":{
"type" : "index_not_found_exception",
"reason" : "no such index",
"resource.type" : "index_or_alias",
"resource.id" : "'index1'",
"index_uuid" : "_na_",
"index" : "'index1'"
```

### Expected Behavior
Reindex task should complete without errors and with a successful index.

### Actual Behavior
Curator completed the task within 30 seconds but elasticsearch logs reported an error.  The new index was not populated.

### Steps to Reproduce the Problem

reindex.yml action file example:
```
actions:
  1:
    action: create_index
    description: "Create index as named"
    options:
      name: new_index
      extra_settings:
        settings:
          number_of_shards: 5
          number_of_replicas: 1
          refresh_interval: -1
  2:
    action: reindex
    description: "merge small indices together"
    options:
      disable_action: False
      ignore_empty_list: True
      wait_for_active_shards: all
      wait_for_completion: True
      wait_interval: 30
      max_wait: -1
      request_body:
        source:
          index: ['index1','index2','index3']
        dest:
          index: new_index
    filters:
    - filtertype: none
  3:
    action: index_settings
    description: "Enable refresh on new index"
    options:
      index_settings:
        index:
          refresh_interval: 60s
      ignore_unavailable: False
      preserve_existing: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: new_index

```

### Specifications

  - Version: curator 5.5.1 and elasticsearch 5.6.9
  - Platform: Redhat Enterprise Linux 7.4 x86_64

## Context (Environment)

Trying to reindex a group of smaller indices into a consolidated index to reduce shard counts.

## Detailed Description

The documentation should be updated to reflect the proper list syntax for the reindex action or the request_body configuration.  If the syntax is correct, a potential bug in curator should be addressed to convert the list into the proper syntax for Elasticsearch.

Related Elastic documentation: https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docs-reindex.html

**Comment by bschneiders** [comment]
This appears to be specific to using environment variables for a templated action file.  If I test with a static example like above, it actually works as documented.  However, if I use environment variables, while they work reliably for individual indices and all other settings, it gets the error described for lists.

```
$ export MYLIST="['dataset_1802941547','dataset_1799202629']"
$ cat test.yml
actions:
  1:
    action: create_index
    description: "Create index as named"
    options:
      name: dataset_r
      extra_settings:
        settings:
          number_of_shards: 5
          number_of_replicas: 1
          refresh_interval: -1
  2:
    action: reindex
    description: "merge small indices together"
    options:
      disable_action: False
      ignore_empty_list: True
      wait_for_active_shards: all
      wait_for_completion: True
      wait_interval: 30
      max_wait: -1
      request_body:
        source:
          index: ${MYLIST}
        dest:
          index: dataset_r
    filters:
    - filtertype: none
  3:
    action: index_settings
    description: "Enable refresh on new index"
    options:
      index_settings:
        index:
          refresh_interval: 60s
      ignore_unavailable: False
      preserve_existing: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: dataset_r
$ curator ./test.yml
...
2018-07-20 18:56:47,798 DEBUG              elasticsearch    log_request_success:86   < {"completed":true,"task":{"node":"JX_1361sSSe6ftc9R_cLJA","id":72235171,"type":"transport","action":"indices:data/write/reindex","status":{
  "total" : 0,
  "updated" : 0,
  "created" : 0,
  "deleted" : 0,
  "batches" : 0,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0
},"description":"reindex from [['dataset_1802941547','dataset_1799202629']] to [dataset_r]","start_time_in_millis":1532112977762,"running_time_in_nanos":127688,"cancellable":true},"error":{
  "type" : "index_not_found_exception",
  "reason" : "no such index",
  "resource.type" : "index_or_alias",
  "resource.id" : "['dataset_1802941547','dataset_1799202629']",
  "index_uuid" : "_na_",
  "index" : "['dataset_1802941547','dataset_1799202629']"
}}
2018-07-20 18:56:47,799 DEBUG              curator.utils             task_check:1645 running_time_in_nanos = 0.000127688
2018-07-20 18:56:47,799 INFO               curator.utils             task_check:1653 Task "reindex from [['dataset_1802941547','dataset_1799202629']] to [dataset_r]" completed at 2018-07-20T18:56:17Z.
2018-07-20 18:56:47,799 DEBUG              curator.utils            wait_for_it:1754 Response: True
2018-07-20 18:56:47,799 DEBUG              curator.utils            wait_for_it:1759 Action "reindex" finished executing (may or may not have been successful)
...
```

But if I use a static file with the same list, it succeeds:

```
actions:
  1:
    action: create_index
    description: "Create index as named"
    options:
      name: dataset_r
      extra_settings:
        settings:
          number_of_shards: 5
          number_of_replicas: 1
          refresh_interval: -1
  2:
    action: reindex
    description: "merge small indices together"
    options:
      disable_action: False
      ignore_empty_list: True
      wait_for_active_shards: all
      wait_for_completion: True
      wait_interval: 30
      max_wait: -1
      request_body:
        source:
          index: ['dataset_1802941547','dataset_1799202629']
        dest:
          index: dataset_r
    filters:
    - filtertype: none
  3:
    action: index_settings
    description: "Enable refresh on new index"
    options:
      index_settings:
        index:
          refresh_interval: 60s
      ignore_unavailable: False
      preserve_existing: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: dataset_r
```
