### ISSUE TITLE
exit code 0 (success) despite schema error

### ISSUE THREAD

**Issue by passing** [elastic/curator#1249]
using curator version 5.5.4, we had rolled out a configuration by accident with the following content:
``` 
  1-logstash-access-misc-1:
    action: rollover
    description: rollover index logstash-access-misc
    options:
      name: logstash-access-misc-write
      conditions:
        max_docs: 10gb
      continue_if_exception: True
      extra_settings:
        index.number_of_shards: 1
```

since this is wrong (max_docs needs to be changed to max_size), curator exits without doing any action:
```
{"@timestamp": "2018-07-31T09:44:26.142Z", "function": "result", "linenum": 65, "loglevel": "ERROR", "message": "Schema error: expected int for dictionary value @ data['conditions']['max_docs']", "name": "curator.validators.SchemaCheck"}
```

unfortunately, curator doesn't exit with exit code 1 as described in the documentation:
https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/exit-codes.html
because of this, the test (dry-run) done in our deployment pipeline did not block the release.
