### ISSUE TITLE
Action: index_settings and option: ignore_unavailable: True (doesn't work)

### ISSUE THREAD

**Issue by srolskyi** [elastic/curator#1257]
My action.yml:

```
    action: index_settings
    description: >-
      Set my-index indices older than 2 month to be read only (block writes)
    options:
      disable_action: False
      index_settings:
        index:
          blocks:
            write: True
      ignore_unavailable: True
      preserve_existing: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: 'my-index\.'
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y-%m'
      unit: months
      unit_count: 2
```
So, option **ignore_unavailable: True** doesn't work, because I really don't have index: my-index.2018-06
I read the doc:

> When the ignore_unavailable option is **False** and an index is missing, or if the request is to apply a static setting and the index is opened, the index setting request will fail. The ignore_unavailable option allows these indices to be skipped, when set to **True**.

If I understood correctly it's mean that if index doesn't exist (missing) action will be skipped. But I got an error:
```
{"@timestamp": "2018-08-14T10:38:32.326Z", "function": "run", "linenum": 146, "loglevel": "INFO", "message": "Preparing Action ID: 402, \"index_settings\"", "name": "curator.cli"}
{"@timestamp": "2018-08-14T10:38:32.341Z", "function": "run", "linenum": 167, "loglevel": "INFO", "message": "Trying Action ID: 402, \"index_settings\": Set my-index indices older than 2 month to be read only (block writes)", "name": "curator.cli"}
{"@timestamp": "2018-08-14T10:38:32.403Z", "function": "run", "linenum": 180, "loglevel": "ERROR", "message": "Unable to complete action \"index_settings\".  No actionable items in list: <class 'curator.exceptions.NoIndices'>", "name": "curator.cli"}
```
and the next action was skipped. Maybe am I missing something? I want next rule: if an index doesn't exist, skipped this actions, and try to next action.
