### ISSUE TITLE
Reindex on ElasticSearch fails but Curator continues to execute script

### ISSUE THREAD

**Issue by wiesniak** [elastic/curator#1260]
Curator performs reindex and ES fails, but Curator continues execution.

### Expected Behavior
Curator should break process and exit with error when error occurs during reindex operation.

### Actual Behavior
Curator continues processing, executing next steps.

### Steps to Reproduce the Problem
1. Create test index:
```
actions:
  1:
    action: create_index
    description: Create the test index
    options:
      name: test_index
      extra_settings:
        settings:
          number_of_shards: 5
          number_of_replicas: 1
        mappings:
          testindexmodel:
            properties:
              testId:
                type: keyword
              price:
                index: false
                type: float
      disable_action: False
```
2. Load data
```
PUT test_index/testindexmodel/1
{
    "testId" : "1",
    "price" : 123.4
}

PUT test_index/testindexmodel/2
{
    "testId" : "2",
    "price" : 123.4,
    "count" : 223
}
PUT test_index/testindexmodel/3
{
  "testId": "3",
  "price": 245.7
}
```
3. Execute upgrade script
```
actions:
  1:
    action: create_index
    description: Create the test index
    options:
      name: test_index_new
      extra_settings:
        settings:
          number_of_shards: 5
          number_of_replicas: 1
        mappings:
          testindexmodel:
            properties:
              testId:
                type: keyword
              price:
                index: false
                type: float
              count:
                index: false
                type: byte
      disable_action: False
  2:
    description: Copy data to the new index
    action: reindex
    options:
      disable_action: False
      continue_if_exception: False
      wait_interval: 9
      max_wait: -1
      request_body:
        source:
          index: test_index
        dest:
          index: test_index_new
    filters:
    - filtertype: none
  3:
    action: delete_indices
    description: Delete obsolete index
    options:
      timeout_override: 300
      continue_if_exception: False
    filters:
      - filtertype: pattern
        kind: regex
        value: '^test_index$'
```
4. Validate documents count - one should be missing.

### Specifications

  - Version: curator-5.5.4-amd64, ElasticSearch: 6.2.2
  - Platform: Curator was run on Windows 10 Pro, 10.0.17134, ES is deployed on Debian 8

## Context (Environment)
Trying to update index with new fields.

## Detailed Description
I have an index with specified structure and filled with about 300k documents. During development, index was filled with about 10 documents that had one property not presented in index mapping (it had values like 150, 225, 250).
Then I created script that "officially" added that property (of byte type) into mapping. Script created new index with new mapping, copied documents and deleted old index (thats a simplified scenario, but it does not matter here). Script executed successfully, but then I noticed that new index lacks a lot of documents.
When I rerun that script with DEBUG logging level I spotted that during reindex error occured, but Curator continued with next steps. Error details:
```
2018-08-23 09:37:27,702 INFO               elasticsearch    log_request_success:83   GET [ES URL]/_tasks/8vBUrfIaQKifX0tqTUUbzg%3A1867459 [status:200 request:0.143s]
2018-08-23 09:37:27,702 DEBUG              elasticsearch    log_request_success:85   > None
2018-08-23 09:37:27,702 DEBUG              elasticsearch    log_request_success:86   < {"completed":true,"task":{"node":"8vBUrfIaQKifX0tqTUUbzg","id":1867459,"type":"transport","action":"indices:data/write/reindex","status":{
  "total" : 3,
  "updated" : 0,
  "created" : 2,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0
},"description":"reindex from [test_index] to [test_index_new]","start_time_in_millis":1535009846497,"running_time_in_nanos":70501857,"cancellable":true,"headers":{}},"response":{
  "took" : 70,
  "timed_out" : false,
  "total" : 3,
  "updated" : 0,
  "created" : 2,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [
    {
      "index" : "test_index_new",
      "type" : "testindexmodel",
      "id" : "2",
      "cause" : {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse [count]",
        "caused_by" : {
          "type" : "illegal_argument_exception",
          "reason" : "Value [223] is out of range for a byte"
        }
      },
      "status" : 400
    }
  ]
}}
2018-08-23 09:37:27,703 DEBUG              curator.utils             task_check:1645 running_time_in_nanos = 0.070501857
2018-08-23 09:37:27,703 INFO               curator.utils             task_check:1653 Task "reindex from [test_index] to [test_index_new]" completed at 2018-08-23T09:37:26Z.
2018-08-23 09:37:27,703 DEBUG              curator.utils            wait_for_it:1754 Response: True
2018-08-23 09:37:27,704 DEBUG              curator.utils            wait_for_it:1759 Action "reindex" finished executing (may or may not have been successful)
2018-08-23 09:37:27,704 DEBUG              curator.utils            wait_for_it:1777 Result: True
```
I don't expect ES to succeed with faulty data, but I'd be happier if Curator could fail here instead of dropping original index as I specified in my upgrade script.
