### ISSUE TITLE
Rollover- Assigning new alias to rolled over Index

### ISSUE THREAD

**Issue by Sujeet1604** [elastic/curator#1278]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

We are using two aliases like index_read & index_write. While rolling over index_read alias, we are mapping index_read to new index. Which is not given in curator rollover extra settings. 

Below is how we are doing it through REST call:
`POST /xg_test_sql_write/_rollover 
{
  "conditions": {
    "max_docs": "1"
  },
  "aliases": {
    "xg_test_sql_read": {}
  }
}`

I expect the same behaviour when rolling over aliases using curator. Does this exists in curator rollover??

1.Yes: how to provide read alias name to new index?
2.No: any alternatives?

Please help us with this query.

**Comment by Sujeet1604** [comment]
@untergeek , I think it won't change much as [elasticsearch.py](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/indices.py)

**Comment by pavolloffay** [comment]
Are there any updates on this?

**Comment by untergeek** [comment]
Not yet, sorry. I'm no longer a full time developer, so I don't get to dedicate as much time to this as I would like.

**Comment by pavolloffay** [comment]
Would you accept a PR adding aliases to https://curator.readthedocs.io/en/latest/actionclasses.html#rollover action?

**Comment by pavolloffay** [comment]
Could you please propose a workaround with the current version of curator? 

We have to call `_rollover` API and add the newly created index into the read alias. How this can be accomplished with the current curator?

**Comment by untergeek** [comment]
The best I can offer is to use the Curator API in conjunction with the Elasticsearch API and script it yourself. There simply isn't a non-API breaking work-around available for this right now.

**Comment by pavolloffay** [comment]
I have played with curator and created the following action files which can be used to 

Create index `jaeger-span-archive-000001` and put it into read and write aliases.
```yml
actions:
  1:
    action: create_index
    description: Create archive index.
    options:
      name: jaeger-span-archive-000001
      continue_if_exception: False
      disable_action: False
  2:
    action: alias
    description: Create read alias for archive index.
    options:
      name: jaeger-span-archive-read
      continue_if_exception: False
      disable_action: False
    add:
      filters:
        - filtertype: pattern
          kind: prefix
          value: jaeger-span-archive
  3:
    action: alias
    description: Create write alias for archive index.
    options:
      name: jaeger-span-archive-write
      continue_if_exception: False
      disable_action: False
    add:
      filters:
        - filtertype: pattern
          kind: prefix
          value: jaeger-span-archive
```

Rollover the index and put the newly created index into read alias.
```yml
actions:
  1:
    action: rollover
    description: Rollover the index associated with write alias.
    options:
      name: jaeger-span-archive-write
      conditions:
        max_age: 1s
      continue_if_exception: False
      disable_action: False

  3:
    action: alias
    description: Create write alias for archive index.
    options:
      name: jaeger-span-archive-read
      continue_if_exception: False
      disable_action: False
    add:
      filters:
        - filtertype: alias
          aliases:
            - jaeger-span-archive-write
```

The second action is an alternative to:
```json
url -ivX POST -H "Content-Type: application/json" localhost:9200/jaeger-span-archive-write/_rollover -d '{
  "conditions": {
    "max_age":  "1s",
    "max_docs":  1
  },
  "aliases": {
    "jaeger-span-archive-read": {}
  }
}'
```

@untergeek I am wondering if the action file can be done atomically, eg. if the last item fails would  it rollback previous changes? Is the curl command I have posted done atomically?  Is it guaranteed that new index is also put to read alias?
