### ISSUE TITLE
Log format is not consistent + allow to configure log pattern

### ISSUE THREAD

**Issue by sta-szek** [elastic/curator#1282]
Bug:
Logs contains exceptions thrown by python code. It does not follow log format which forces me to add complex grok filter (in case I want to deliver logs to ELK).

Feature request:
I would like to have possibility to configure log pattern. This will be really helpful if I want to have logs from different services / components in one index in ES. Having that I can search all logs using the same fields.

Example usage:
log-format: { "application_name": "es-curator", "message": "%m", ....}

### Expected Behavior
Logs have consistent format, even for exceptions thrown by underlying components.

### Actual Behavior
Logs are inconsistent:
`default` format:
```
2018-10-05 14:06:38,739 INFO      Preparing Action ID: 1, "delete_indices"
/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py:135: UserWarning: Connecting to xxxx.com using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

```
`json` format:
```
{"@timestamp": "2018-10-05T14:03:44.090Z", "function": "run", "linenum": 146, "loglevel": "INFO", "message": "Preparing Action ID: 1, \"delete_indices\"", "name": "curator.cli"}
{"@timestamp": "2018-10-05T14:03:44.336Z", "function": "run", "linenum": 167, "loglevel": "INFO", "message": "Trying Action ID: 1, \"delete_indices\": Clean up ES by deleting old jaeger indices", "name": "curator.cli"}
{"@timestamp": "2018-10-05T14:04:54.220Z", "function": "run", "linenum": 175, "loglevel": "INFO", "message": "Skipping action \"delete_indices\" due to empty list: <class 'curator.exceptions.NoIndices'>", "name": "curator.cli"}
{"@timestamp": "2018-10-05T14:04:54.221Z", "function": "run", "linenum": 196, "loglevel": "INFO", "message": "Action ID: 1, \"delete_indices\" completed.", "name": "curator.cli"}
{"@timestamp": "2018-10-05T14:04:54.221Z", "function": "run", "linenum": 197, "loglevel": "INFO", "message": "Job completed.", "name": "curator.cli"}
/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py:135: UserWarning: Connecting to xxxx.com using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

### Steps to Reproduce the Problem
```
  config_yml: |-
    ---
    client:
      hosts:
        - xxxx.com
      port: 443
      url_prefix:
      use_ssl: True
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: True
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
```

### Specifications
curator 5.5.4 deployed to k8s using helm chart https://github.com/helm/charts/tree/master/incubator/elasticsearch-curator
