### ISSUE TITLE
Curator allocation set total_shards_per_node

### ISSUE THREAD

**Issue by cushind** [elastic/curator#1287]
## Allocation action allow setting total_shards_per_node

In `actions.py` the allocation constructor default allocation_type is 'require'. This prevents setting the index allocation setting `index.routing.allocation.total_shards_per_node`

```
class Allocation(object):
    def __init__(self, ilo, key=None, value=None, allocation_type='require',
        wait_for_completion=False, wait_interval=3, max_wait=-1,
        ):
```

```
if allocation_type not in ['require', 'include', 'exclude']:
            raise ValueError(
                '{0} is an invalid allocation_type.  Must be one of "require", '
                '"include", "exclude".'.format(allocation_type)
            )
```

```
bkey = 'index.routing.allocation.{0}.{1}'.format(allocation_type, key)
```

### Expected Behavior
I expect to be able to set the index allocation setting `index.routing.allocation.total_shards_per_node`

### Actual Behavior
Puts the setting `index.routing.allocation.require.total_shards_per_node`.

### Steps to Reproduce the Problem
1. Example action:
```
    actions:
      1:
        action: allocation
        description: >-
          Apply shard allocation routing to modify total shards per node
        options:
          key: total_shards_per_node
          value: '4'
        filters:
        - filtertype: pattern
          kind: prefix
          value: my-index-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 1
```

### Specifications

  - Version: 5.5.4

## Our Use Case
We are running a private elasticsearch cluster with two hot nodes and 1 warm node. We have the setting `total_shards_per_node` set to evenly distribute shards for a given index across our hot nodes. In order to use the shrink action (shrink api) all shards have to be on the same node. If `total_shards_per_node` is less than the total number of shards we cannot combine shards on a node before shrinking. Therefore I would like to be able to change this setting without having to reindex.

**Comment by cushind** [comment]
I can put in a PR with a fix if needed.

**Comment by untergeek** [comment]
This setting, in spite of containing the `index` and `allocation` is about shard routing, specifically.  You should be able to use the [`index_settings`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/index_settings.html) to change other index settings, including this one.

**Comment by cushind** [comment]
@untergeek Tried with `index_settings`, and curator complains that "routing" is not a valid index setting. So I actually don't think this works with `index_settings`.

**Comment by BlakeWills** [comment]
I can confirm that using the `index_settings` action works for this. Example action:

```
2:
    action: index_settings
    description: "Set index.routing.allocation.total_shards_per_node to allow all primaries on single shard."
    options:
      index_settings:
        index:
          routing:
            allocation:
              total_shards_per_node: '6'
      continue_if_exception: False
      disable_action: False
      allow_ilm_indices: true
```

I still get a warning saying that this isn't a known setting so it may or may not work, but checking the settings after confirms it applied.
