### ISSUE TITLE
Reindex fails if source is empty when using REINDEX_SELECTION with ignore_empty_list: True

### ISSUE THREAD

**Issue by BenjaminDebotte** [elastic/curator#1297]
### Context

I'm using `elasticsearch-curator` to reindex several daily indices before yesterday into a weekly index. 
For this matter we have a task defined as this:

```YAML
  12:
    description: >-
      Reindex all previous daily 'dummy-test-index' indices starting yesterday to weekly index
    action: reindex
    options:
      ignore_empty_list: True # Doesn't work here. Curator will fail. Need to be fixed.
      wait_for_completion: True
      wait_interval: 9
      max_wait: -1
      request_body:
        source:
          index: REINDEX_SELECTION
        dest:
          index: "<dummy-test-index-{now/d{xxxx:'w'ww}}>"
    filters:
      - filtertype: pattern
        kind: regex
        value: '^dummy-test-index-\d{4}\.\d{2}\.\d{2}$'
      - filtertype: kibana
        exclude: True
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 1
```

### Expected Behavior
I would expect Elasticsearch-curator to carry-on if no indices is provided in `REINDEX_SELECTION`. `continue_if_exception` is not an option here as the operation is critical. Right now it just stops to cure on the first empty action.

#### JSON Log output
```JSON
{
    "@timestamp": "2018-10-24T09:34:59.078Z",
    "function": "run",
    "linenum": 146,
    "loglevel": "INFO",
    "message": "Preparing Action ID: 12, \"reindex\"",
    "name": "curator.cli"
} {
    "@timestamp": "2018-10-24T09:34:59.087Z",
    "function": "run",
    "linenum": 167,
    "loglevel": "INFO",
    "message": "Trying Action ID: 12, \"reindex\": Reindex all previous daily 'dummy-test-index' indices starting yesterday to weekly index",
    "name": "curator.cli"
} {
    "@timestamp": "2018-10-24T09:34:59.316Z",
    "function": "run",
    "linenum": 186,
    "loglevel": "ERROR",
    "message": "Failed to complete action: reindex.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: Source index must be list of actual indices. It must not be an empty list.",
    "name": "curator.cli"
}
```

### Steps to Reproduce the Problem
  1. Create any reindex task, with an existing destination and `ignore_empty_list: True`
  2. Provide filters which will resolve to empty
  3. Curator will fail with `Source index must be list of actual indices. It must not be an empty list` message.

### Specifications

  - Version: Elasticsearch-curator 5.5.4 from pip
  - Running in docker image `alpine:3.4` over Centos 6
