### ISSUE TITLE
Can not update index.unassigned.node_left.delayed_timeout via index settings action

### ISSUE THREAD

**Issue by m1nkman** [elastic/curator#1300]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue

We operate a multiple large ES clusters with tiered storage. I added a curator action to set index.unassigned.node_left.delayed to a larger value for indices that had been moved to our long term storage tier. 

### Expected Behavior

I expected index.unassigned.node_left.delayed on each of the filtered indices to be changed

### Actual Behavior

```
WARNING   "unassigned" is not a setting Curator recognizes and may or may not work.
ERROR     Unable to complete action "index_settings".  No actionable items in list: <class 'curator.exceptions.NoIndices'>
```
### Steps to Reproduce the Problem

  1. Create an index default settings
  2. Run curator with index settings action
```
action: index_settings
    description: Increase unassigned.node_left.delayed_timeout to 5m
    options:
      index_settings:
        index:
          unassigned:
            node_left:
              delayed_timeout: 5m
```

### Specifications

  - Version: Curator 5.5.1
  - Platform: Ubuntu 16.04.5
  - Subsystem: ElasticSearch 6.3.1

## Context (Environment)

We run multiple very large ES clusters for logging. Due to the size of the clusters, we maintain a system of tiered storage. When indices are no longer being written to, we move them to a read-only tier. The indices are not marked read-only, but the no documents are added to the indices on this tier. Since the indices are static, we wanted to increase the node_left.delayed_timeout so that when instances restart(thank you cloud), we would experience a shorter recovery times. We use curator's allocation action to move the indices to the read-only tier and wanted to have curator increase the node_left timeout at the same time.

## Detailed Description

Add the 'unassigned' group to the dynamic index settings whitelist.
