### ISSUE TITLE
one delete indices action delete other indices

### ISSUE THREAD

**Issue by like-inspur** [elastic/curator#1318]
My ES environment now only has logstash prefix indices, and doesn't have audit prefix indices. I want to config two delete indices action, but found that delete audit prefix indices delete logstash prefix indices. 

My curator version is 5.5.4 and action_file.yml is like this:
```
    actions:
      1:
        action: delete_indices
        description: "Clean up common log by deleting old indices"
        options:
          ignore_empty_list: True
          timeout_override: 600
          continue_if_exception: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 14
      2:
        action: delete_indices
        description: "Clean up audit log by deleting old indices"
        options:
          ignore_empty_list: True
          timeout_override: 600
          continue_if_exception: True
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: audit-
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
```
curator executation log is like this:
```
2018-11-21 08:00:10,617 INFO      Preparing Action ID: 1, "delete_indices"
2018-11-21 08:00:10,626 INFO      Trying Action ID: 1, "delete_indices": Clean up common log by deleting old indices
2018-11-21 08:00:11,951 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2018-11-21 08:00:11,951 INFO      Action ID: 1, "delete_indices" completed.
2018-11-21 08:00:11,951 INFO      Preparing Action ID: 2, "delete_indices"
2018-11-21 08:00:11,953 INFO      Trying Action ID: 2, "delete_indices": Clean up audit log by deleting old indices
2018-11-21 08:00:11,975 INFO      Deleting selected indices: [u'logstash-2018.11.14']
2018-11-21 08:00:11,975 INFO      ---deleting index logstash-2018.11.14
2018-11-21 08:00:12,201 INFO      Action ID: 2, "delete_indices" completed.
2018-11-21 08:00:12,201 INFO      Job completed.
```

**Comment by untergeek** [comment]
First and foremost, use DEBUG logging instead of INFO, which will give you much more information.

Second, you have multiple `filters` blocks within each action, which is not supposed to happen. It could be causing the issues you are seeing.

Namely, the first filters block in each action contains the prefix filter. Instead, you are ending up with only an `age` filter. It's as though the first action has only:

```
filters:
- filtertype: age
  source: name
  direction: older
  timestring: '%Y.%m.%d'
  unit: days
  unit_count: 14
```
And the second action's filter only has:
```
filters:
- filtertype: age
  source: name
  direction: older
  timestring: '%Y.%m.%d'
  unit: days
  unit_count: 7
```

This is why the second action is deleting Logstash prefixed indices. It's only looking for indices with a `%Y.%m.%d` timestring, and that older than only 7 days. `logstash-2018.11.14` matches that, as it's older than 7 days. The first action's filters match nothing because there is nothing older than 14 days.

Your action's filter blocks should look like:
```
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 14
```
and
```
        filters:
        - filtertype: pattern
          kind: prefix
          value: audit-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
```
Note the omission of the extra `filters` line in each case.

Enabling DEBUG logging will show you what your filters have been parsed and processed into. Elevated logging is your first line of defense, as is running in `--dry-run` mode to see the output before actually running. Using `--dry-run` with DEBUG will show all kinds of troubleshooting info worth digging into.
