### ISSUE TITLE
Snapshot action not starting but delete snapshot is working fine

### ISSUE THREAD

**Issue by rmorandell-pgum** [elastic/curator#1362]
About the elastic API I have no problems to make snapshot and restore it. Also on the CLI via a CURL it works flawlessly.
Even deleting the snapshot works without problems via the curator. But if I want to take a snapshot into my FS repo via the curator, the curator starts the actionFile but then shows no output. Also no error message. The log level is set to "DEBUG".

Here the YML for the delete and the LOG to it ...

**delete snapshot YML WORKING**

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 2 days
      (based on creation_date), for 'snapshot' prefixed snapshots.
    options:
      repository: kibana_backup
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: snapshot
    - filtertype: age
      source: creation_date
      direction: older
      unit: minutes
      unit_count: 1
```
**Log**

...
2019-02-25 11:30:22,143 DEBUG     curator.validators.SchemaCheck               __init__:27   "filter" config: {'filtertype': 'age', 'source': 'creation_date', 'direction': 'older', 'unit': 'minutes', 'unit_count': 1, 'exclude': False, 'epoch': None, 'timestring': None}
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist        iterate_filters:514  Parsed filter args: {'filtertype': 'age', 'source': 'creation_date', 'direction': 'older', 'unit': 'minutes', 'unit_count': 1, 'exclude': False, 'epoch': None, 'timestring': None}
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist        iterate_filters:523  Filter args: {'source': 'creation_date', 'direction': 'older', 'unit': 'minutes', 'unit_count': 1, 'exclude': False, 'epoch': None, 'timestring': None}
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist        iterate_filters:524  Pre-instance: ['snapshot_20190225']
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist          filter_by_age:265  Starting filter_by_age
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist          filter_by_age:268  Point of Reference: 1551090562
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist           __actionable:44   Snapshot snapshot_20190225 is actionable and remains in the list.
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist            __excludify:69   Remains in actionable list: Snapshot "snapshot_20190225" age (1551088917), direction: "older", point of reference, (1551090562)
2019-02-25 11:30:22,143 DEBUG       curator.snapshotlist        iterate_filters:526  Post-instance: ['snapshot_20190225']
2019-02-25 11:30:22,143 INFO      curator.actions.delete_snapshots             do_dry_run:978  DRY-RUN MODE.  No changes will be made.
2019-02-25 11:30:22,144 INFO      curator.actions.delete_snapshots             do_dry_run:986  DRY-RUN: delete_snapshot: snapshot_20190225 with arguments: {'repository': 'kibana_backup', 'retry_interval': 120, 'retry_count': 3}
2019-02-25 11:30:22,144 INFO                 curator.cli                    run:196  Action ID: 1, "delete_snapshots" completed.
2019-02-25 11:30:22,144 INFO                 curator.cli                    run:197  Job completed.

**And here is the yml actionfile for the snapshot that do nothing**
```
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: snapshot
    description: >-
      Snapshot selected indices to 'repository' with the snapshot name or name
      pattern in 'name'.  Use all other options as assigned
    options:
      repository: kibana_backup
      name: 'kibana-%Y%m%d%H%M%S'
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
     kind: prefix
     value: .kibana
     exclude: False
```

**And here the log**

2019-02-25 11:35:07,789 DEBUG                curator.cli                    run:108  Client and logging options validated.
2019-02-25 11:35:07,789 DEBUG                curator.cli                    run:112  default_timeout = 30
2019-02-25 11:35:07,789 DEBUG                curator.cli                    run:116  action_file: /etc/curator/snapshot_kibana.yml

I also tried to use a regex. But nothing changes

    - filtertype: pattern
     kind: regex
     value: '^\.kibana.*$'
     exclude: False

**curator.yml**

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - 127.0.0.1
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logfile:
  logformat: default
  blacklist: []
#  blacklist: ['elasticsearch', 'urllib3']
```

**Specifications**

  - Version: 5.6.0
  - Platform: CentOS7
  - Elasticsearch: 6.5.4
  -minimum_wire_compatibility_version" : "5.6.0"
   -minimum_index_compatibility_version" : "5.0.0"

**Comment by untergeek** [comment]
Please encapsulate your pasted content inside triple back ticks, like this:

    ```
    PASTE HERE
    ```

I can't see your YAML as it is formatted without this, and based on what I'm seeing in your log output, it could be a YAML formatting error (because it never gets past checking the yaml file).

**Comment by rmorandell-pgum** [comment]
Hi Aaron, thank you for the answer. I edited the issue so u can see the yml formatted.

**Comment by untergeek** [comment]
Try updating the indent of the filters:

```
filters:
- filtertype: pattern
  kind: prefix
  value: .kibana
  exclude: False
```

The indent levels I see suggest that the later keys are not part of the array element `filtertype: pattern`
