### ISSUE TITLE
num_segments not detected properly on force merge action

### ISSUE THREAD

**Issue by waxie** [elastic/curator#1364]
### Expected Behavior
To run force merge on indexes with large number of segments

### Actual Behavior
The indexes get removed from the actionable index list, claiming they have 0 segments

### Steps to Reproduce the Problem
  1. run forcemerge

action config:
```
          4:
            action: forcemerge
            description: "Run forcemerge"
            options:
              max_num_segments: 1
              continue_if_exception: True
              ignore_empty_list: True
              disable_action: False
            filters:
            - filtertype: age
              source: creation_date
              direction: older
              unit: days
              unit_count: 1
            - filtertype: pattern
              kind: regex
              value: ".*(_logs_).*"
```

### Specifications

  - Version: curator 5.6.0 elastic 6.5.4
  - Platform: ubuntu

## Detailed Description

curator claims this index for example has 0 segments and removes it from actionable list. DEBUG output:
```
2019-03-08 13:56:03,438 DEBUG          curator.indexlist       __not_actionable:39   Index access_logs_dus1-2019.03.06 is not actionable, removing from list.
2019-03-08 13:56:03,438 DEBUG          curator.indexlist            __excludify:58   Removed from actionable list: access_logs_dus1-2019.03.06 has 3 shard(s) + 2 replica(s) with a sum total of 0 segments.
```

But checking with elastic shows it does have more segments than that:
```
$ curl -s host:port/access_logs_dus1-2019.03.06/_stats | python -m json.tool | grep -A 1 segments
            "segments": {
                "count": 46,
--
            "segments": {
                "count": 143,
--
                "segments": {
                    "count": 46,
--
                "segments": {
                    "count": 143,
```
