### ISSUE TITLE
ILM filter not using working_list

### ISSUE THREAD

**Issue by tiempososcuros** [elastic/curator#1389]
### Expected Behavior
Curator run correctly whitout errors when there are no indexes to eliminate.

### Actual Behavior
Curator displays an error message when there are no indexes to eliminate.

### Steps to Reproduce the Problem

> [root@elasticsearch-node1 ~]# curator /root/.curator/action.yml
> 2019-04-25 12:14:05,311 INFO      Preparing Action ID: 1, "delete_indices"
> 2019-04-25 12:14:05,326 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 3
> months (based on index name). Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
> 2019-04-25 12:14:05,409 ERROR     Failed to complete action: delete_indices.  <class 'ValueError'>: list.remove(x): x not in list

### Specifications
CentOS Linux release 7.6.1810 (Core)
Curator 5.7.3

File curator.yml

> client:
>   hosts: [ "elasticsearch-node1:9200", "elasticsearch-node2:9200" ]
>   url_prefix:
>   use_ssl: False
>   certificate:
>   client_cert:
>   client_key:
>   ssl_no_validate: False
>   http_auth:
>   timeout: 30
>   master_only: False
> 
> logging:
>   loglevel: INFO
>   logfile:
>   logformat: default
>   blacklist: ['elasticsearch', 'urllib3']

File action.yml

> actions:
>   1:
>     action: delete_indices
>     description: >-
>       Delete indices older than 3 months (based on index name). Ignore the error if the filter
>       does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
>     options:
>       ignore_empty_list: True
>     filters:
>     - filtertype: age
>       source: name
>       direction: older
>       timestring: '%Y.%m.%d'
>       unit: months
>       unit_count: 3

**Comment by untergeek** [comment]
I can't replicate your results. I just created an empty test cluster in my ECE instance, and tested with the same options you provided:

```
client:
  hosts: [ "52a2fe13bd4a443c931926b3a66f0d4a.ece.REDACTED.net" ]
  port: 9243
  use_ssl: true
  http_auth: 'elastic:REDACTED'
```

```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 3 months (based on index name). Ignore the error if the filter
      does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
    filters:
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: months
        unit_count: 3
```

```
$ curator --version
curator, version 5.7.3
[buh@centos7-pkg-test ~]$ curator --config client.yml emptytest.yml
2019-04-25 12:14:05,548 INFO      Preparing Action ID: 1, "delete_indices"
2019-04-25 12:14:05,662 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 3 months (based on index name). Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2019-04-25 12:14:05,700 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2019-04-25 12:14:05,701 INFO      Action ID: 1, "delete_indices" completed.
2019-04-25 12:14:05,701 INFO      Job completed.
```

Are you sure you have everything indented properly in your `action.yml` file? I can't tell because you didn't paste it between triple back ticks, like this:

    ```
    PASTE HERE
    ```

**Comment by tiempososcuros** [comment]
> I can't replicate your results. I just created an empty test cluster in my ECE instance, and tested with the same options you provided:
> 
> ```
> client:
>   hosts: [ "52a2fe13bd4a443c931926b3a66f0d4a.ece.REDACTED.net" ]
>   port: 9243
>   use_ssl: true
>   http_auth: 'elastic:REDACTED'
> ```
> ```
> actions:
>   1:
>     action: delete_indices
>     description: >-
>       Delete indices older than 3 months (based on index name). Ignore the error if the filter
>       does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
>     options:
>       ignore_empty_list: True
>     filters:
>       - filtertype: age
>         source: name
>         direction: older
>         timestring: '%Y.%m.%d'
>         unit: months
>         unit_count: 3
> ```
> ```
> $ curator --version
> curator, version 5.7.3
> [buh@centos7-pkg-test ~]$ curator --config client.yml emptytest.yml
> 2019-04-25 12:14:05,548 INFO      Preparing Action ID: 1, "delete_indices"
> 2019-04-25 12:14:05,662 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 3 months (based on index name). Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
> 2019-04-25 12:14:05,700 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
> 2019-04-25 12:14:05,701 INFO      Action ID: 1, "delete_indices" completed.
> 2019-04-25 12:14:05,701 INFO      Job completed.
> ```
> Are you sure you have everything indented properly in your `action.yml` file? I can't tell because you didn't paste it between triple back ticks, like this:
> 
> ```
> ```
> PASTE HERE
> ```
> ```

Sorry. Paste the action.yml file:
```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 3 months (based on index name). Ignore the error if the filter
      does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: months
      unit_count: 3
```
