### ISSUE TITLE
ReadonlyREST plugin for Elasticsearch requires X-Api-key header to be set

### ISSUE THREAD

**Issue by vetler** [elastic/curator#1409]
### Expected Behavior
ReadonlyREST plugin requires X-Api-key to be set to the correct value, it should be possible to set this.

### Actual Behavior
It is not possible to configure Curator to set the X-Api-key header when accessing Elasticsearch.

### Steps to Reproduce the Problem
  1. Run Elasticsearch with ReadonlyREST enabled and API key required to access Elasticsearch
  1. Try to run Curator
  1. It fails, because Curator can't set the X-Api-key header with the required API key

## Context (Environment)
Example readonlyrest configuration (set in elasticsearch.yml:
```
readonlyrest:
  access_control_rules:
    - name: "api key"
      type: allow
      api_keys: ["foo"]
```

## Detailed Description
I propose adding an api_key setting in the config file.
