### ISSUE TITLE
ILM policy + allow_ilm_indices + rollover issue

### ISSUE THREAD

**Issue by krisATelastic** [elastic/curator#1418]
## Issue
When using the rollover function of Curator against indices within a cluster, it seems to ignore the `allow_ilm_indices` when the `options.name` is an alias and will roll the index behind that alias regardless

### Expected Behavior
If the indices within that alias that are being rolled are tied to an ILM policy, do not rollover

### Actual Behavior
I found in testing that omitting the `allow_ilm_indices` setting or even setting to false, the rollover job will still roll my test Metricbeat index which is tied to an ILM policy;
_GET metricbeat-6.7.1-*/_settings_
```
{
  "metricbeat-6.7.1-2019.06.26-000001" : {
    "settings" : {
      "index" : {
        "lifecycle" : {
          "name" : "beats-default-policy",
          "rollover_alias" : "metricbeat-6.7.1"
        },
...
}
```
After executing the action job
```
2019-06-26 06:27:11,840 INFO      Preparing Action ID: 1, "rollover"
2019-06-26 06:27:11,849 INFO      Trying Action ID: 1, "rollover": Rollover the index associated with index 'metricbeats-system'
2019-06-26 06:27:11,852 INFO      Performing index rollover
2019-06-26 06:27:12,018 INFO      Old index metricbeat-6.7.1-2019.06.26-000001 rolled over to new index metricbeat-6.7.1-2019.06.26-000002
2019-06-26 06:27:12,018 INFO      Action ID: 1, "rollover" completed.
2019-06-26 06:27:12,018 INFO      Job completed.
```
_action.yml_
```
---
actions:
  1:
    action: rollover
    description: Rollover the index associated with index 'metricbeats-system'
    options:
      continue_if_exception: true
      name: metricbeat-6.7.1
      conditions:
        max_docs: 18000000
        max_size: 1m
```
### Steps to Reproduce the Problem
1. Build Elasticsearch cluster, with any form of data source, Metricbeat is easy as it ties to ILM
2. Configure metricbeat with ILM policy, simpler just to use `metricbeat setup -e`...

### Specifications

  - Version: `6.7.1`
  - Platform: `Ubuntu 18.04 LTS`
  - Subsystem:

## Detailed Description
Reporting this issue as it may affect other users migrating over to ILM who may be using aliases and rollover policies also, it may affect them too. Either a docs tweak or a code change would most likely help avoid any issues with clashing policies.
