### ISSUE TITLE
Remote end closed connection without response curator

### ISSUE THREAD

**Issue by ep4sh** [elastic/curator#1449]
### Expected Behavior
```
2019-01-09 11:10:06,701 INFO      All indices appear to have been restored.
2019-01-09 11:10:06,702 INFO      Action ID: <22>, "restore" completed.
```
### Actual Behavior
```
2019-08-02 03:39:05,457 INFO      Restoring indices "['applicationlog-trace-2019.01.01']" from snapshot: logs-weeks-13_2018.12.31_2019.01.09
2019-08-02 03:43:16,676 ERROR     Failed to complete action: restore.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: ConnectionError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))) caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))
```
### Steps to Reproduce the Problem

  1. 
```
curator --config curator.yml restore.yml
```
  2. In the restore.py :
```
client = es.Elasticsearch([{'host': HOST, 'port': 443, 'use_ssl': True, 'ssl-no-validate': False, 'timeout': 600}])
```
  3. In the config.yml :
```
client:
  hosts: bla-bla.bla.com
  port: 443
  url_prefix:
  use_ssl: True
  ssl_no_validate: False
  timeout: 30
 
logging:
  loglevel: INFO
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```
### Specifications

Centos 7.6
virualenv 3
elasticsearch         7.0.2    
elasticsearch-curator 5.7.6

## Detailed Description
My ES host bla-bla.bla.com working and response all the requests. 
4 months ago my restore script worked fine, but I have no changes by this time (checked via git)
Possible changes are versions of the **elasticsearch** and **elasticsearch**-curator packages, but the same time snapshot creating with curator works fine (with similar settings)
