### ISSUE TITLE
field_stats based age filter fails on frozen indices

### ISSUE THREAD

**Issue by sastorsl** [elastic/curator#1480]
## field_stats based age filter fails on frozen indices
When using field_stats with the field `@timestamp` to determine the age of an index curator fails if any index which is to be considered has been [frozen](https://www.elastic.co/guide/en/elasticsearch/reference/master/frozen-indices.html).

Refering to the docs of field based age filters for curator:
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_age.html
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_field.html

### Expected Behavior
Would expect that curator can detect a frozen index and consequenly either ignore it or search it with [ignore_throttled=false](https://www.elastic.co/guide/en/elasticsearch/reference/master/searching_a_frozen_index.html)

### Actual Behavior
Curator fails during examination of which indices to perform the required action to.

`2019-10-29 11:37:24,164 ERROR     Failed to complete action: forcemerge.  <class 'curator.exceptions.ActionError'>: Field "@timestamp" not found in index "logstash-myindex-2019.19.weekly"`

### Steps to Reproduce the Problem

1. Create an index
2. Freeze the index after writes are complete
3. Create an index which should match, and one that should not match the action
3. Run curator with the following action example:

```yaml
actions:
  1:
    action: delete_indices
    description: >-
      default: Delete indices older than 1 days for indices prefixed with "logstash-".
      Ignore the error if the filter does not result in an actionable list of
      indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: field_stats
      field: '@timestamp'
      stats_result: max_value
      direction: older
      unit: days
      unit_count: 1
      exclude:
```

The test is run with the following command:

```bash
docker run \
    --rm \
    --net=elk \
    -v /root/elk/curator/curator.yml:/curator.yml:ro \
    -v /root/elk/curator/action.yml:/action.yml:ro \
    -v /etc/localtime:/etc/localtime:ro \
    praseodym/elasticsearch-curator:5.8.1 \
    --dry-run \
    --config /curator.yml /action.yml
```

Observe that an error is produced, and that the action is aborted.

`2019-10-29 11:37:24,164 ERROR     Failed to complete action: forcemerge.  <class 'curator.exceptions.ActionError'>: Field "@timestamp" not found in index "logstash-myindex-2019.19.weekly"`

The `continue_if_exception: True` setting will skip to the next action, but no action will be performed on matching indices.

### Specifications

  - Version: 5.8.1
  - Platform: RHEL7 - Running `curator` in docker.
  - Subsystem:

## Context (Environment)
We are freezing older indices to keep them searchable while reducing the need for JVM heap.
Since we are using curator to delete even older indices and forcemerge indices which are no longer written to this error makes it impossible for us to either freeze or continue using curator.

## Detailed Description
Make `curator` "aware" of frozen indices.

**Comment by untergeek** [comment]
Thank you for submitting this. I fear, however, that while name and metadata based age filters are likely to work with frozen indices, field_stats is query based and may not.

**Comment by sastorsl** [comment]
What we are using `field_stats` for is to determine if an index is indeed inactive, i.e. no writes for x days, and therefore rely on `field_stats.

So a delete or forcemerge action need to be able to query a frozen index.
We also have a variety of indices, daily, weekly, monthly and yearly, the patterns are so different.
Still we want to know that the index is no longer being written to before any "destructive" action (delete, forcemerge, freeze).

**Comment by untergeek** [comment]
Indeed, a frozen filter has been planned for a while. That could be included alongside this request as a separate one.

I am somewhat concerned, however, about the time it may take to query multiple frozen indices for `field_stats` (with `ignore_throttled=false` enabled) in order to put an index list together. While the code could support this, I don't want—and I'm sure users don't either—repeat runs of Curator to take minutes just to analyze what the min/max values of the timestamps are. Also, due to the nature of queries against frozen indices, they may need to be done serially, increasing the time required for finding this information. While your indices may not be slow to query while frozen, others may have very large counts of frozen indices which may be quite large.


For the next major release, I will be adding functionality which will store index stats between runs. This is intended chiefly to prevent needing to query the same information repeatedly when very little will have changed _between actions._ However, extending this functionality to prevent needing to re-discover frozen indices and their index stats may be of added value here.

**Comment by untergeek** [comment]
> What we are using field_stats for is to determine if an index is indeed inactive, i.e. no writes for x days, and therefore rely on `field_stats`.

This is exactly why using the rollover API is preferred over age-based indices. Once an index has rolled over, you never have to wonder if it's still being updated. If you have a compelling reason to keep using named indices and Curator to determine if they are old enough, then that's fine. But I highly recommend using aliases and rollover and maintaining indices based on size, as a lower shard count can be assured in this manner.

**Comment by sastorsl** [comment]
We will definitely look into the rollover API, but we're not there yet.
Still I think that adding an _option_ to filtertype `age` with a `field_stats` source to query frozen indices is a reasonable request.

Perhaps this could work:

```yaml
   - filtertype: age
     source: field_stats
     field: '@timestamp'
     stats_result: max_value
     direction: older
     unit: days
     unit_count: 30
     frozen: ignore   # ignore|query|false
```
The default could be to fail on frozen indices, while you can actively opt to either ignore or query on frozen indices.

Regarding identifying frozen indices the [Monitoring frozen indices page](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring_frozen_indices.html) states that you can query for the `sth` field.

I'm not anywhere near creating a PR for curator but this small script can maybe be the basis for a bold adventurer, and at least some help for somebody else stumbling in on this issue:

```bash
#!/bin/bash
# elk-index-list-frozen.sh
# 29.10.2019, sastorsl, List indices
URL="http://localhost:9200/_cat/indices/${1:-}?v&s=index&h=i,sth"

curl -s -XGET "${URL:?}" | awk '$2=="true" { print $1 }'
```

**Comment by untergeek** [comment]
No, I don't think it's an unreasonable request. I will get to this. But I can't give you a timeline on when it will be released.

**Comment by sastorsl** [comment]
I've been able to workaround the issue _for now_ by excluding known frozen indices.

```yaml
  2:
    action: forcemerge
    description: >-
      default: forceMerge indices older than "1" day(s) for indices not written to for 1 day,
      except for yearly|monthly|weekly indices.
    options:
      max_num_segments: 1
      ignore_empty_list: True
      delay: 120
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: pattern
      kind: regex
      value: 'logstash-.+(yearly|monthly|weekly)'
      exclude: True
    - filtertype: pattern
      kind: regex
      value: '^logstash-frozenindex1-2019\.(19|20)\.weekly|logstash-frozenindex2-2019\.05\..+\.batch$'
      exclude: True
    - filtertype: age
      source: field_stats
      field: '@timestamp'
      stats_result: max_value
      direction: older
      unit: days
      unit_count: 1
      exclude:
```
