### ISSUE TITLE
WARNING when using count filtertype with use_age option

### ISSUE THREAD

**Issue by hulkk** [elastic/curator#1488]
### Expected Behavior

WARNING event should not be logged in case where closed indices are explicitly excluded from result set.

### Actual Behavior

WARNING event is logged for each action that has count filtertype used with use_age option. No matter if closed indices are explicitly excluded.
`WARNING - Cannot get age information from closed indices unless source="name".  Omitting any closed indices.`

### Steps to Reproduce the Problem

  1. Create Curator action file (example below)
  2. Run Curator

Action file
```
actions:
  1:
    action: allocation
    description: "move indices from hot nodes to warm nodes"
    options:
      key: node_type
      value: warm
      allocation_type: require
      wait_for_completion: true
      timeout_override:
      continue_if_exception: false
      disable_action: false
      ignore_empty_list: true
    filters:
    - filtertype: closed
      exclude: true
    - filtertype: pattern
      kind: prefix
      value: <redacted>_
    - filtertype: count
      count: 1
      use_age: true
      source: creation_date
```

### Specifications

  - Version: 5.7.6
  - Platform: CentOS 7.6
