### ISSUE TITLE
Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>

### ISSUE THREAD

**Issue by marouen10** [elastic/curator#1490]
Dear all,

I tried to use curator to delete indices for Elasticsearch "older than 10 days", but I always get Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>.

curator --config /etc/curator/curator.config /etc/curator/del-old-logs.yml
2019-12-04 03:47:17,361 INFO      Preparing Action ID: 1, "delete_indices"
2019-12-04 03:47:17,361 INFO      Creating client object and testing connection
2019-12-04 03:47:17,364 INFO      Instantiating client object
2019-12-04 03:47:17,365 INFO      Testing client connectivity
2019-12-04 03:47:17,368 INFO      Successfully created Elasticsearch client object with provided settings
2019-12-04 03:47:17,369 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 90 days (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2019-12-04 03:47:17,396 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2019-12-04 03:47:17,396 INFO      Action ID: 1, "delete_indices" completed.
2019-12-04 03:47:17,397 INFO      Job completed.
Here the del-old-logs.yml settings:

actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 90 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 10
      exclude:

The logstash indexes are still displayed and not deleted.

curator_cli show_indices
2019-12-04 03:46:59,848 INFO      Instantiating client object
2019-12-04 03:46:59,849 INFO      Testing client connectivity
2019-12-04 03:46:59,853 INFO      Successfully created Elasticsearch client object with provided settings
.kibana_1
.kibana_task_manager
logstash-2019.10.04-000001
logstash-2019.11.03-000002
logstash-2019.12.03-000003

curl -XGET 'localhost:9200/_cat/indices?v&pretty'
health status index                              uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .kibana_task_manager               X7EUsto6S7eFI64VfP3oOw   1   0          2            0     31.3kb         31.3kb
yellow open   logstash-2019.11.03-000002         cQ2U8JC3RZ2sQXNtrWGesQ   1   1  228373323            0       32gb           32gb
yellow open   logstash-2019.12.03-000003         pv927GgbSBeRtq3oZxDFbw   1   1    7864141            0      1.1gb          1.1gb
yellow open   logstash-2019.10.04-000001         V2XZ370dQJ6wg43J36kfCA   1   1  219073641            0     27.2gb         27.2gb
green  open   .kibana_1                          n4wwHCrIRma2kOVel_juBg   1   0        707           14    417.1kb        417.1kb

Do you know the root cause ?
Thank you in advance

**Comment by untergeek** [comment]
If you run Curator with loglevel set to DEBUG you will likely see an extra message that indicates that these logstash indices have an ILM (Index Lifecycle Management) policy affixed. Curator will not operate against indices with an ILM policy unless you set [`allow_ilm_indices: true`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/ilm-and-curator.html).

Read more [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/ilm.html).

**Comment by marouen10** [comment]
Thanks a lot.
This solved my issue.

**Comment by marouen10** [comment]
> 
> 
> If you run Curator with loglevel set to DEBUG you will likely see an extra message that indicates that these logstash indices have an ILM (Index Lifecycle Management) policy affixed. Curator will not operate against indices with an ILM policy unless you set [`allow_ilm_indices: true`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/ilm-and-curator.html).
> 
> Read more [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/ilm.html).

Thanks a lot.
This solved the issue.

**Comment by bittu664** [comment]
Same problem here, I want to delete indices but not work it returns ``` Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>```   I am also added this parameter  ``` allow_ilm_indices: true ```  but it won't work for me. for your kind information, I am using EFK stack  (opendistro elasticsearch & kibana , Fluentd)

![finall](https://user-images.githubusercontent.com/28609215/74931653-1362cb00-5406-11ea-9224-8c46afc7ac70.png)

Here is my configuration:- 
`` curator.yaml ```

```
---
client:
  hosts:
    - localhost
  port: 9200
  url_prefix: 
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: admin:admin
  timeout: 3600
  master_only: False
  

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```


``` delfinal.yaml ```

```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 45 days (based on index name), for kube
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: kube
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 45
```

When I am checking my kube pattern indices it is still there. so how to delete my indices which is older than 30 days or a  **specific indices**

**Comment by kasim457** [comment]
> 
> 
> If you run Curator with loglevel set to DEBUG you will likely see an extra message that indicates that these logstash indices have an ILM (Index Lifecycle Management) policy affixed. Curator will not operate against indices with an ILM policy unless you set [`allow_ilm_indices: true`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/ilm-and-curator.html).
> 
> Read more [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/ilm.html).

@untergeek ,  I added same settings in my action.yaml section ( values.yaml) and did not see any progress.   Could you guide me what is missing in action.yaml to enforce deletion action.

```
2021-03-08 01:00:07,786 DEBUG          curator.indexlist       empty_list_check:226  Checking for empty list
2021-03-08 01:00:07,787 INFO                 curator.cli                    run:180  Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2021-03-08 01:00:07,787 INFO                 curator.cli                    run:201  Action ID: 1, "delete_indices" completed.
2021-03-08 01:00:07,787 INFO                 curator.cli                    run:202  Job completed.
   
```

Here is the output of acton.yaml

```
action_file_yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          allow_ilm_indices: true
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 90
          field:
          stats_result:
          epoch:
          exclude: False
```

**Comment by kasim457** [comment]
```
 config_yml: |-
    ---
    client:
      hosts:
        - elasticsearch-master
      port: 9200
      url_prefix:
      use_ssl: True
      certificate: '/certs/elastic-stack-ca.pem'
      client_cert: '/certs/elastic-certificate.pem'
      ssl_no_validate: True
      http_auth: "XXXXX:XXXXXXXX"
      timeout: 30
      master_only: False
    logging:
      loglevel: DEBUG
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
```

**Comment by untergeek** [comment]
This is not enough of the debug log to diagnose anything concretely. All I can tell is that in the end, Curator had filtered all indices.

**Comment by Adnan029** [comment]
I am facing the same issue.

Find the error below
opt/bitnami/python/lib/python3.9/site-packages/elasticsearch_curator-5.8.4-py3.9.egg/curator/actions.py:151: SyntaxWarning: "is" with a literal. Did you mean "=="?
/opt/bitnami/python/lib/python3.9/site-packages/elasticsearch_curator-5.8.4-py3.9.egg/curator/actions.py:151: SyntaxWarning: "is" with a literal. Did you mean "=="?
2023-03-01 06:49:16,137 INFO      Preparing Action ID: 1, "delete_indices"
2023-03-01 06:49:16,137 INFO      Creating client object and testing connection
2023-03-01 06:49:16,148 INFO      Instantiating client object
2023-03-01 06:49:16,149 INFO      Testing client connectivity
/opt/bitnami/python/lib/python3.9/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
2023-03-01 06:49:16,475 INFO      Successfully created Elasticsearch client object with provided settings
2023-03-01 06:49:16,480 WARNING   allow_ilm_indices: true
2023-03-01 06:49:16,480 WARNING   Permitting operation on indices with an ILM policy
2023-03-01 06:49:16,480 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 3 days
/opt/bitnami/python/lib/python3.9/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: this request accesses system indices: [.apm-agent-configuration, .apm-custom-link, .async-search, .kibana_7.17.3_001, .kibana_task_manager_7.17.3_001, .tasks], but in a future major version, direct access to system indices will be prevented by default
  warnings.warn(message, category=ElasticsearchWarning)
2023-03-01 06:49:16,675 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2023-03-01 06:49:16,675 INFO      Action ID: 1, "delete_indices" completed.
2023-03-01 06:49:16,675 INFO      Job completed.

I am using the below configuration.

action_file.yml:
----
---
actions:
  1:
    action: delete_indices
    description: "Delete indices older than 3 days"
    options:
      allow_ilm_indices: true
      ignore_empty_list: true
      disable_action: false
    filters:
    - filtertype: pattern
      kind: prefix
      value: filebeat-
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 3
config.yml:
----
client:
  hosts:
    -  http://elasticsearch-master
  port: 9200

**Comment by untergeek** [comment]
Curator 5.8 is deprecated. Use v6, v7, or v8. 

Also, Python 3.9 would not be approved for use with Curator 5.8

**Comment by Adnan029** [comment]
Thanks, So which Python version we should use

**Comment by Adnan029** [comment]
I am using the python version 
Python 3.8.0
And elasticsearch curator version 
curator, version 7.0.0.


But still, I am getting the below output while deleting the older index for more than 3 days.
Even I am having index older than Month. Also no ILM applied on indices

2023-03-02 15:34:36,625 INFO      Preparing Action ID: 1, "delete_indices"
2023-03-02 15:34:36,626 INFO      Creating client object and testing connection
2023-03-02 15:34:36,628 INFO      Instantiating client object
2023-03-02 15:34:36,629 INFO      Testing client connectivity
2023-03-02 15:34:36,637 INFO      Successfully created Elasticsearch client object with provided settings
2023-03-02 15:34:36,640 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 3 days
/usr/local/lib/python3.8/dist-packages/elasticsearch7/connection/base.py:200: ElasticsearchWarning: this request accesses system indices: [.apm-agent-configuration, .apm-custom-link, .asyn
c-search, .kibana_7.17.6_001, .kibana_task_manager_7.17.6_001, .security-7, .tasks], but in a future major version, direct access to system indices will be prevented by default
  warnings.warn(message, category=ElasticsearchWarning)
2023-03-02 15:34:36,709 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2023-03-02 15:34:36,709 INFO      Action ID: 1, "delete_indices" completed.
2023-03-02 15:34:36,709 INFO      Job completed.
root@ip-10-16-1-41:/# vim config.yml
root@ip-10-16-1-41:/# vim action.yml
root@ip-10-16-1-41:/# curator --config config.yml action.yml
2023-03-02 15:35:30,273 INFO      Preparing Action ID: 1, "delete_indices"
2023-03-02 15:35:30,273 INFO      Creating client object and testing connection
2023-03-02 15:35:30,276 INFO      Instantiating client object
2023-03-02 15:35:30,276 INFO      Testing client connectivity
2023-03-02 15:35:30,282 INFO      Successfully created Elasticsearch client object with provided settings2023-03-02 15:35:30,284 WARNING   allow_ilm_indices: true2023-03-02 15:35:30,284 WARNING   Permitting operation on indices with an ILM policy
2023-03-02 15:35:30,284 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 3 days
/usr/local/lib/python3.8/dist-packages/elasticsearch7/connection/base.py:200: ElasticsearchWarning: this request accesses system indices: [.apm-agent-configuration, .apm-custom-link, .asyn
c-search, .kibana_7.17.6_001, .kibana_task_manager_7.17.6_001, .security-7, .tasks], but in a future major version, direct access to system indices will be prevented by default
  warnings.warn(message, category=ElasticsearchWarning)
2023-03-02 15:35:30,341 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2023-03-02 15:35:30,341 INFO      Action ID: 1, "delete_indices" completed.
2023-03-02 15:35:30,341 INFO      Job completed.

**Comment by untergeek** [comment]
It means that there were no actionable indices found or matched with what you are filtering for—even though you have set `allow_ilm_indices: True` and all that, you still aren't having any indices to act on.

The list of indices it shows doesn't include a single `filebeat-` prefixed index, so I don't know why it's a surprise that it's giving you an empty list exception. I recommend running with `loglevel: DEBUG` in order to see how it's filtering/selecting indices. `INFO` is telling you it can't find any indices, but not what it started from and how it got there. `DEBUG` logging will show that.

**Comment by untergeek** [comment]
Ah. That would explain it. You misunderstand how filters work. For each action, they are all logically AND-ed together. It is impossible for one of your indices to be prefixed with both `stage-dbmodel-` AND `dev-3rdparty-`, and you have several more of those being combined. That appears to be why it isn't working. Please refer to the [filter documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/7.0/filters.html) with regards to filter chaining. What you are attempting to do might look better like this:



```
---
actions:
  1:
    action: delete_indices
    description: "Delete indices older than 3 days"
    options:
      allow_ilm_indices: true
      ignore_empty_list: true
      disable_action: false
    filters:
    - filtertype: pattern
      kind: regex
      value: '^(dev-verify-|dev-dbmodel-|stage-3rdparty-|dev-3rdparty-).*$'
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 3
  2:
    action: delete_indices
    description: "Delete indices older than 1 day"
    options:
      allow_ilm_indices: true
      ignore_empty_list: true
      disable_action: false
    filters:
    - filtertype: pattern
      kind: prefix
      value: stage-dbmodel-
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 1
```
