### ISSUE TITLE
Schema Error on Filters with Valid Data Type

### ISSUE THREAD

**Issue by corey-hammerton** [elastic/curator#1493]
## To submit a bug or report an issue
Using the following action file named reindex.yaml:

```
---
actions:
  1:
    action: reindex
    options:
      max_wait: -1
      wait_for_completion: true
      wait_interval: 9
      request_body:
        source:
          index: mm-group-metrics-2019-11-*
        dest:
          index: mm-group-metrics-2019-11
  2:
    action: delete_indices
    filters:
    - filtertype: pattern
      kind: regex
      value: '^mm-group-metrics-2019-11-'
```

Curator is complaining about a Schema error with the following message:

`2019-12-09 16:28:54,045 ERROR     Schema error: expected list for dictionary value @ data['filters']`

### Expected Behavior
Expected behaviour is running `curator --dry-run reindex.yaml` should execute without issue. It's a dry run and should output log messages about what it would attempt to do.

### Actual Behavior

Executing `curator --dry-run reindex.yaml` outputs only the following log line:

`2019-12-09 16:28:54,045 ERROR     Schema error: expected list for dictionary value @ data['filters']
`

### Steps to Reproduce the Problem

  1. Install Curator 5.7.6 via YUM
  2. Create the reindex.yaml file
  3. Execute `curator --dry-run reindex.yaml`

### Specifications

  - Version: 5.7.6
  - Platform: CentOS 7
  - Subsystem:

## Context (Environment)
We are attempting to reindex logs from a daily pattern to a monthly pattern through Curator. It's not possible to implement a data retention policy.

**Comment by untergeek** [comment]
Did you use tabs or spaces for your YAML? YAML will have issues with spaces.

```
  2:
    action: delete_indices
    filters:
      - filtertype: pattern
        kind: regex
        value: '^mm-group-metrics-2019-11-'
```
You can also force the issue by adding spaces to the subsequent lines under filters, as above.

**Comment by corey-hammerton** [comment]
We are using 2-spaces. Changing to tabs didn't help.

This config is automatically generated.

**Comment by corey-hammerton** [comment]
Weird part is we have another actions file with filters and delete_indices actions with filters and it still executes without issue. Here's the config in part:

```
actions:
  '1':
    action: delete_indices
    description: Delete flume-log- prefixed indices created more than 15 days ago
    options:
      ignore_empty_list: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: flume-log-
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 15
  '2':
    action: delete_indices
    description: Delete elasticsearch-log- prefixed indices created more than 15 days
      ago
    options:
      ignore_empty_list: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: elasticsearch-log-
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 15
```

**Comment by untergeek** [comment]
🤦‍♂ I got that backwards. Tabs == bad with YAML. Spaces are preferred. 

It's saying that `filters` is a dictionary value. Is there some hidden character after the colon?

```
  2:
    action: delete_indices
    filters:
    - filtertype: pattern
      kind: regex
      value: '^mm-group-metrics-2019-11-'
```
Something here is causing the YAML to be misinterpreted. 

```
index: mm-group-metrics-2019-11-*
```
While this is not likely related, I do recommend encapsulating anything with a wildcard in single quotes as a safety measure.

**Comment by untergeek** [comment]
And I still recommend additional indent for the filters here as a test:

```
  2:
    action: delete_indices
    filters:
      - filtertype: pattern
        kind: regex
        value: '^mm-group-metrics-2019-11-'
```

**Comment by corey-hammerton** [comment]
It seems that there is an issue with the wildcard in the reindex. The following config passes the schema check:

```
---
actions:
  '1':
    action: reindex
    options:
      ignore_empty_list: true
      max_wait: -1
      wait_for_completion: true
      wait_interval: 9
      request_body:
        source:
          index: REINDEX_SELECTION
        dest:
          index: "mm-group-metrics-2019-11"
    filters:
      - filtertype: pattern
        kind: regex
        value: "^mm-group-metrics-2019-11-"
  '2':
    action: delete_indices
    options:
      ignore_empty_list: true
    filters:
      - filtertype: pattern
        kind: regex
        value: "^mm-group-metrics-2019-11-"
```
