### ISSUE TITLE
Shrink action: create alias with original index name pointing to final index

### ISSUE THREAD

**Issue by eedugon** [elastic/curator#1495]
A common use case when shrinking indices consists of creating aliases of the shrunk indices using the names of the original indices.

The extra_setting `aliases` available is not clear in the [docs](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_extra_settings.html#_shrink), and the purpose of it when using the shrink action to shrink multiple indices is not clear also.

It would be great if curator is able to create an alias using the original name of the index after having deleted the original index (`delete_after: True` should be mandatory for this to happen). This could easily be applied when the action is used to shrink multiple indices, as one alias will be created for every shrunk + deleted index.

**Comment by singerxt** [comment]
@eedugon I have to do exactly same thing. Did you resolve this problem in another way?

**Comment by eedugon** [comment]
Thanks @singerxt for your feedback and the link to the similar issue reported.
I will leave up to @untergeek to decide which one to keep open.
We haven't solved this yet.

**Comment by singerxt** [comment]
I figured out a different solution that works for me and handling indices with aliases and indices without aliases. A snapshot repository is required for this solution.

```yml
actions:
  '1':
    action: shrink
    description: 'Shrink all indexes to 1 shard. All original indexes will be deleted!'
    options:
      disable_action: false
      ignore_empty_list: true
      shrink_node: DETERMINISTIC
      node_filters:
        permit_masters: false
        exclude_nodes:
          - not_this_node
      number_of_shards: 1
      number_of_replicas: 1
      shrink_prefix: null
      shrink_suffix: '-shrinked'
      copy_aliases: true
      delete_after: true
      wait_for_active_shards: 1
      extra_settings:
        settings:
          index.codec: best_compression
          index.mapping.total_fields.limit: 10000
      wait_for_completion: true
      wait_for_rebalance: true
      wait_interval: 9
      max_wait: -1
    filters:
      -
        filtertype: pattern
        kind: regex
        value: kibana
        exclude: true
  '2':
    action: snapshot
    options:
      repository: repo-ue1-1-prod0-content-legacy2
      name: null
      ignore_unavailable: false
      include_global_state: true
      partial: false
      wait_for_completion: true
      skip_repo_fs_check: false
      timeout_override: null
      continue_if_exception: false
      disable_action: false
    filters:
        -
          filtertype: pattern
          kind: regex
          value: kibana
          exclude: true
  '3':
    action: delete_indices
    options:
      ignore_empty_list: true
      timeout_override: null
      continue_if_exception: true
      disable_action: false
    filters:
      -
        filtertype: pattern
        kind: regex
        value: kibana
        exclude: true
  '4':
    action: restore
    description: 'Restore all indexes and remove shrink suffix from index name'
    options:
      repository: repo-ue1-1-prod0-content-legacy2
      name: null
      indices: null
      include_aliases: True
      rename_pattern: (.+)-shrinked
      rename_replacement: $1
      wait_for_completion: true
      wait_interval: 10
    filters:
      -
        filtertype: none
```
