### ISSUE TITLE
curator snapshot doesn't include all indices

### ISSUE THREAD

**Issue by linkwrt** [elastic/curator#1513]
**backup using:**
curator - not working
curator_cli - works

_All indices are included only when snapshot is done with curator_cli._

CLI example, all indices are included.

```shell
curator_cli \
--config ~/.curator/curator.yml \
snapshot \
--repository elasticsearch_backup_repo \
--filter_list '{"filtertype":"none"}'
```

Using curator command with action.yml //  only indices with prefix . are included in snapshot
Example for action.yml

```yaml
actions:
  1:
    action: snapshot
    description: >-
      Snapshot indices.
      Wait for the snapshot to complete.  Do not skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    # name of the repository path given while registering the bkp folder
    options:
      repository: elasticsearch_backup_repo

    # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name: mybkp-%Y%m%d%H%M%S
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      disable_action: False
    filters:
      - filtertype: pattern
        kind: regex
        value: "^(.*).*$"
```
