### ISSUE TITLE
Bypass ILM check for snapshot/restore actions

### ISSUE THREAD

**Issue by aliciascott** [elastic/curator#1514]
Reference: https://github.com/elastic/curator/issues/1401

### Expected Behavior
With ES versions 7.x and higher, Metricbeat and Filebeat use ILM policies by default,  Along with `.watcher-history` now using an ILM policy by default.
We expect Curator to `Snapshot` all indices regardless of ILM policy.

In the documentation we know curator won’t touch anything with an[ ILM policy](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/ilm-and-curator.html). 

### Workaround:
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_allow_ilm.html

```
actions:
  1:
    action: snapshot
    options:
      allow_ilm_indices: true
      repository: Repo_01
      name: curator3_snapshot
      ignore_unavailable: True
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      disable_action: False
    filters:
      - filtertype: none
```

### Actual Behavior

It can be possible to not realize you have any ILM policies configured, since these Beats modules are configuring ILM policies by default, and you may end up loosing days of Snapshots of Beats indices without realizing it.
Curator also does not report this as an error, it merely skips these indices.

### Steps to Reproduce the Problem

  1. Configure a Curator `action.yml` with a `Snapshot` policy
  2. Configure an ES 7.x cluster with Metricbeat or Filebeat 7.x
  3. Note in your `_snapshot/Repo/_all` output you are missing any indices that have an ILM policy

### Specifications

  - Version: 7.x
  - Platform:
  - Subsystem:

## Context (Environment)

This problem can become more apparent with users who continue to use Curator for snapshots and do not realize they also have ILM policies configured due to default behavior of those modules.
