### ISSUE TITLE
curator snapshot not working for all indices

### ISSUE THREAD

**Issue by linkwrt** [elastic/curator#1515]
Curator doesn't backup all indices in snapshot.
Indices with prefix . are included in backup.
Indices with format name-auditlog-2020.02.06  are not included in backup
I used :

```shell
[machine #] curator action_snapshot.yml
```

```yaml
actions:
  1:
    action: snapshot
    description: >-
      Snapshot indices.
    options:
      repository: elasticsearch_backup_repo
      name: snapshot-%Y%m%d%H%M%S
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      disable_action: False
    filters:
    -  filtertype: none
```

I checked snapshot logs and custom indices are missing.

If i use curator_cli, snapshot include all indices.

```shell
curator_cli \
--config ~/.curator/curator.yml \
snapshot \
--repository elasticsearch_backup_repo \
--filter_list '{"filtertype":"none"}'
```
