### ISSUE TITLE
Error: TransportError(503, u'master_not_discovered_exception', None)

### ISSUE THREAD

**Issue by bittu664** [elastic/curator#1516]
I want to delete my 10 days Kubernetes logs, so when I applying this configuration it shows me this error. I am using this version  ``` curator, version 5.8.1 ```

```  curator ./delete_indices.yml --config ./curator.yaml   ```

![curator2](https://user-images.githubusercontent.com/28609215/74740192-69a60180-5280-11ea-83f3-4faa765d0e86.png)

My configuration is :- 
```curator.yaml ```

```
---
client:
  hosts:
    - 192.89.03.01
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: abc:abc
  timeout: 3600
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```

 
``` delete_indices.yml ```

```
---
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 45 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: kube*-
      exclude:
    - filtertype:  age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 10
      exclude:
```
