### ISSUE TITLE
Failed to complete action: create_index already exists.

### ISSUE THREAD

**Issue by bittu664** [elastic/curator#1517]
I am using curator version ``` curator, version 5.8.1 ```  I am trying to create indices but it shows me this error  !
``` ERROR     Failed to complete action: create_index.  <class 'curator.exceptions.FailedExecution'>: Index <web-app2-metrics-{now/M-1M{YYYY.MM}}> already exists. ```
![already](https://user-images.githubusercontent.com/28609215/74838566-ccaf9b00-5349-11ea-8bb7-432c84b5f22c.png)

 what's going wrong am I writing the wrong script?  if yes then what's the correct method or script. Here is my configurations as follows:-

``` curator ./create-indices.yaml --config ./curator.yaml ```

``` curator.yaml ```

``` 
---
client:
  hosts:
    - localhost
  port: 9200
  url_prefix: 
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: admin:admin
  timeout: 3600
  master_only: False
  

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```
 

``` create-indices.yaml ```

```
---
actions:
  create_web-app3-metrics:
    action: create_index
    description: "Create Index with Last Months Date in Month Format - web-app3-metrics-2017.11"
    options:
      name: '<web-app2-metrics-{now/M-1M{YYYY.MM}}>'
      extra_settings:
        settings:
          number_of_shards: 5
          number_of_replicas: 2
        continue_if_exception: True
        disable_action: False

  create_web-app4-metrics:
    action: create_index
    description: "Create Index with Daily Format 12 Hours from Now - web-app4-metrics-2017.12.05"
    options:
      name: '<web-app2-metrics-{now/d{YYYY.MM.dd|+12:00}}>'
      extra_settings:
        settings:
          number_of_shards: 5
          number_of_replicas: 2
        continue_if_exception: True
        disable_action: False
  
```
