### ISSUE TITLE
delete_indices not working return error "due to empty list: <class 'curator.exceptions.NoIndices'>"

### ISSUE THREAD

**Issue by bittu664** [elastic/curator#1518]
Same problem here, I want to delete indices but not work it returns Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'> I am also added this parameter 
``` allow_ilm_indices: true```  but it won't work for me. for your kind information, I am using EFK stack (opendistro elasticsearch & kibana , Fluentd)

![finall](https://user-images.githubusercontent.com/28609215/74932212-45286180-5407-11ea-830b-10add7f31a5a.png)

Here is my configuration:-
`` curator.yaml ```

```
---
client:
  hosts:
    - localhost
  port: 9200
  url_prefix: 
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: admin:admin
  timeout: 3600
  master_only: False
  

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3'] 
```

``` delfinal.yaml ```

```

actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 45 days (based on index name), for kube
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: kube
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 45
```

When I am checking my kube pattern indices it is still there. so how to delete my indices which is older than 30 days or a **specific indices**
