### ISSUE TITLE
Treat invalid date as warning and continue processing

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/curator#1545]
## To submit a bug or report an issue

Curator exits with an error immediately when it comes across a invalid date in an index name.

### Expected Behavior

Report a warning, skip the index and continue on.

### Actual Behavior

Curator exits with an error and stops processing further actions.

### Steps to Reproduce the Problem

  1. Create an index with an invalid date for example `log_network-switch__v1_2023-05-42`.
  1. Attempt to parse the date with a filter like this:

     ```YAML
     - filtertype: age
       source: name
       timestring: '%Y-%m-%d'
       direction: younger
       unit: days
       unit_count: 34
     ```

### Specifications

  - Version: 5.8.1
  - Platform: GNU/Linux
  - Subsystem: filtertype: age

## Context (Environment)

The issue has a real world impact in that if an index with invalid date exists, curator will not process any actions after it. If we are talking about a delete job, the cluster could run out of disk space and not be able to start new indices.
