### ISSUE TITLE
takes at least 2 arguments (2 given)

### ISSUE THREAD

**Issue by joshuansu0897** [elastic/curator#1554]
## Bug/Issue
```bash
2020-08-31 00:00:00,270 ERROR     Failed to complete action: delete_snapshots.  <type 'exceptions.TypeError'>: get() takes at least 2 arguments (2 given)
```

### Steps to Reproduce the Problem
try to use this config with curator
```yaml
actions:
  1:
    action: delete_snapshots
    options:
      repository: repository-name
      retry_interval: 120
      retry_count: 3
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 14
```

### Specifications
  - Version: 5.8.1
  - Platform: Ubuntu

## How solve the problem?
curate are using `elasticsearch==7.1.0` in [requirements.txt](https://github.com/elastic/curator/blob/master/requirements.txt), you can upde to use `elasticsearch==7.9.1` and the problem should be solve
