### ISSUE TITLE
alias remove that finds nothing to remove should not error

### ISSUE THREAD

**Issue by iamnoah** [elastic/curator#1576]
### Expected Behavior

There should be some way to configure an alias action that removes time based indexes from an alias to not fail when nothing needs to be done without resorting to continue_if_exception.

### Actual Behavior

Even if ignore_empty_list and warn_if_no_indices are True, an ActionError is still thrown because there are no add or remove operations.

### Steps to Reproduce the Problem

Create a few monthly indexes. e.g.,  myindex_2020-10, myindex_2020-11, myindex_2020-12. 

Add them all to an alias "myindex".

Run this action to include only the last month and this month in the alias:
```yaml
1:
  action: alias
  options:
    name: myindex
    ignore_empty_list: True
    warn_if_no_indices: True
  remove:
   filters:
    - filtertype: pattern
      kind: prefix
      value: myindex_
    - filtertype: period
      unit: months
      range_from: -1200
      range_to: -2
      source: name
      timestring: "%Y-%m"
```

On the first run, it is fine, it removes the 2020-10 index.

Run it again and it fails because there is nothing to do. 

## Context (Environment)

I just want to run a command that makes sure my aliases are in the correct state. If there is nothing to do, that's GOOD! But I can't have confidence in the outcome if I am forced to ignore all exceptions.

Curator Version is 5.8.1
