### ISSUE TITLE
Curator does not delete indexes with a hyphen

### ISSUE THREAD

**Issue by cmckinney18** [elastic/curator#1585]
I have found that if an index has a second hyphen, I cannot get curator to delete it... using regex, prefix, suffix, nothing.

Example:
index-version1-2021-01-13  <-- does not delete (or even show in dry run)
index-2021-01-13 <-- works as expected

If I run curator_cli show_indexes, all the indexes show, including the ones with two hyphens.

**Comment by untergeek** [comment]
This is unusual. Please share your YAML configuration so I can see what's going on.

**Comment by cmckinney18** [comment]
Here is one config file:

```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 135 days (based on index name), for elastiflow-4.0.1
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
      timeout_override:
      continue_if_exception: False
    filters:
    - filtertype: pattern
      kind: suffix
      value: '-\d{4}\.\d{2}\.\d{2}'
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 135
```
This shows all the .reporting indexes fine, but none of the elastiflow indexes (elastiflow-4.0.1-%Y.%m.%d).

Another try:
```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 135 days (based on index name), for elastiflow-4.0.1
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
      timeout_override:
      continue_if_exception: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: 'elastiflow-'
      - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 135
```
No indexes returned.
