### ISSUE TITLE
filter_by_count() got an unexpected keyword argument 'pattern'

### ISSUE THREAD

**Issue by dekimsey** [elastic/curator#1588]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue

Using a count filter with the `pattern` argument is not implemented for snapshots. Compare [indexlist.py#L877](https://github.com/elastic/curator/blob/v5.8.2/curator/indexlist.py#L877) to [snapshotlist.py#L335](https://github.com/elastic/curator/blob/v5.8.2/curator/snapshotlist.py#L335).

### Expected Behavior

My goal is to prune snapshots. I was going to use `count` to partition the snapshots into buckets and then purge all but the most successful entry, but that doesn't seem to be supported.

### Actual Behavior

```
2021-02-08 12:15:04,839 INFO      Trying Action ID: 0, "delete_snapshots": Prune snapshots
2021-02-08 12:15:36,528 ERROR     Failed to complete action: delete_snapshots.  <class 'TypeError'>: filter_by_count() got an unexpected keyword argument 'pattern'
```

### Steps to Reproduce the Problem

```
actions:
  0:
    action: delete_snapshots
    description: Prune snapshots
    filters:
    - filtertype: pattern
      kind: regex
      value: '@archive\.'
    - filtertype: state
      state: SUCCESS
    - filtertype: count
      count: 1
      pattern: '^(.*)@archive\.\d{10}$'
      reverse: true
      exclude: true
    options:
      repository: onpremise-archive
      ignore_empty_list: true
```

### Specifications

  - Version: 5.8.3
  - Platform: OSX 11.1
  - Subsystem: Python 3.8.3

## Context (Environment)

Unable to prune snapshots effectively.

## Detailed Description

n/a
