### ISSUE TITLE
delete_snapshots doesn't accept timeout_override value if it's greater than 300 seconds

### ISSUE THREAD

**Issue by shivpathak** [elastic/curator#1600]
## For usage questions and help
topic created: https://discuss.elastic.co/t/curator-timeout-override-parameter-not-working-for-snapshot-delete-action/271473

Perhaps a topic there already has an answer for you!

### Steps to Reproduce the Problem

  1. use below configuration for delete_snapshots action where snapshot deletion took more than 5minutes

```
---
    actions:
      1:
        action: delete_snapshots
        description: >-
          "Delete selected snapshots from 'manual-triggerd' older than 14 matching curator-"
        options:
          repository: manual-triggered
          retry_interval: 120
          retry_count: 3
          ignore_empty_list: True
          timeout_override: 21600
        filters:
        - filtertype: pattern
          kind: prefix
          value: curator-
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: 14
```
  1.

It throws following exception:

```
2021-04-28 06:36:01,541 INFO      Deleting snapshot curator-2021-04-14-06:30:20...
    2021-04-28 06:41:01,695 ERROR     Failed to complete action: delete_snapshots.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: NotFoundError(404, 'snapshot_missing_exception', '[manual-triggered:curator-2021-04-14-06:30:20] is missing')
```
  1.

### Specifications

  - Version: 5.8.1
  - Platform: Kubernetes
  - Subsystem: Linux
