### ISSUE TITLE
If I run shrink after index_settings my index settings are overwritten

### ISSUE THREAD

**Issue by fidsamurai-crelio** [elastic/curator#1641]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

### Expected Behavior

After running index_settings to block writes to my old indices, my next action is to shrink the index which should create a new index as all the pre-shrink conditions are met.

### Actual Behavior

However for some reason before shrinking the index the blocks.write setting reverts to false.

### Steps to Reproduce the Problem

  ```
  5:
    action: index_settings
    description: >-
      Set old indices to read-only
    options:
      disable_action: False #True
      index_settings:
        index:
          blocks:
            write: True
      continue_if_exception: False
      preserve_existing: False
      ignore_unavailable: True
    filters:
      - filtertype: alias
        aliases: <alias>
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 1
  6:
    action: shrink
    description: >-
      Shrink old indices to 1 shard
    options:
      timeout_override: 300
      disable_action: False #True
      continue_if_exception: False
      shrink_node: DETERMINISTIC
      number_of_shards: 1
      number_of_replicas: 0
      shrink_prefix: inactive-
      shrink_suffix: null
      delete_after: False
      post_allocation:
        allocation_type: include
        key: box_type
        value: hot
      wait_for_active_shards: 1
      wait_for_completion: True
      wait_for_rebalance: False
      wait_interval: 30
      extra_settings:
        settings:
          index.blocks.write: true
    filters:
      - filtertype: alias
        aliases: <alias>
      - filtertype: age
        source: creation_date
        direction: younger
        unit: days
        unit_count: 2
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 1
  ```
### Specifications

  - Version: Curator 5.8 ES 6.2
  - Platform: AWS EC2 Instance
  - Subsystem: Ubuntu 16.04 

## Context (Environment)

As ES 6.2 doesn't support ILM we're trying to use curator for ILM.
