### ISSUE TITLE
[docker] untergeek/curator `missing signature key` on server

### ISSUE THREAD

**Issue by sastorsl** [elastic/curator#1674]
### Expected Behavior
That `docker run untergeek/curator` should start curator.

### Actual Behavior
On RedHat Enterprise Linux 7 (RHEL7) getting the curator docker image fails:

Command:

```bash
docker run --rm untergeek/curator:8.0.3
```

output:

```bash
Unable to find image 'untergeek/curator:8.0.3' locally
Trying to pull repository untergeek/curator ... 
/usr/bin/docker-current: missing signature key.
```
Running the same on i.e. Ubuntu 22.04 LTS works as expected, so I expect that it is an issue with the version of RHEL7 docker.

### Steps to Reproduce the Problem
1. Configure docker on RHEL7
2. Try and start undergeek/docker

### Specifications

* Operating system: `Red Hat Enterprise Linux Server release 7.9 (Maipo)`

Docker version, is the bundled docker version for RHEL7

```yaml
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jan  7 13:15:46 2022
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-209.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jan  7 13:15:46 2022
 OS/Arch:         linux/amd64
 Experimental:    false
```

## Context (Environment)
One of our elasticsearch / kibana / logstash (ELK) platforms runs on RHEL7, and we use (used) curator to manage indices.
Since the upgrade to ELK-8 curator has not worked with the old version of curator.

## Detailed Description
It would be great if the docker build could support all major versions of the underlying docker client / server versions.
