### ISSUE TITLE
new curator version breaks the TLS verify functionality

### ISSUE THREAD

**Issue by rgaduput** [elastic/curator#1708]
When upgraded the curator from 8.0.8 to 8.0.10 we have observed that it fails to connect with Elastic with TLS exception even though cert verify is set to `false`, this functionality works just fine if we go back to older version 8.0.8.
please note i have tried the latest version 8.0.12 as well.

### Expected Behavior
Certs verification ignored while connecting to Elasticseach.

### Actual Behavior
Fails to connect with below
```
2024-03-26 12:04:52,549 INFO      Preparing Action ID: 1, "delete_indices"
2024-03-26 12:04:52,550 INFO      Creating client object and testing connection
2024-03-26 12:04:53,051 CRITICAL  Unable to establish client connection to Elasticsearch!
2024-03-26 12:04:53,051 CRITICAL  Exception encountered: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)))
```

### Steps to Reproduce the Problem

  1. Create actions.yml with below content
```
actions:
  1:
    action: delete_indices
    description: "Clean up ES by deleting old indices"
    options:
      continue_if_exception: False
      disable_action: False
      ignore_empty_list: True
    filters:
    - filtertype: kibana
      exclude: True
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 7
```
  2. Create config.yml and set the verify_certs as false
```
elasticsearch:
  client:
    hosts: https://infra-elasticsearch.infra:9200
    verify_certs: false
  other_settings:
    username: ${ES_USER}
    password: ${ES_PASSWD}
```
  3. Run the curator with config and action files
```
  args:
    - '--config'
    - /etc/es-curator/config.yml
    - /etc/es-curator/action_file.yml
```

### Specifications

  - Version: 8.0.10
  - Platform: Kubernetes
  - Subsystem: n/a

## Context (Environment)

Trying to perform Elastic index clean up but ignore the certs while connecting to it since certs are self signed.

**Comment by untergeek** [comment]
Can you provide debug output of this, please?

**Comment by rgaduput** [comment]
@untergeek Hi,
I have tried below config to produce the DEBUG ouput, but the ouput did not changed. May be i have to try something else ?

```
elasticsearch:
  client:
    hosts: https://infra-elasticsearch.infra:9200
    verify_certs: false
  other_settings:
    username: ${ES_USER}
    password: ${ES_PASSWD}
logging:
  loglevel: DEBUG
```
