### ISSUE TITLE
Execute by configuration file

### ISSUE THREAD

**Issue by pickypg** [elastic/curator#343]
The idea is that you could create a configuration file that allowed a single run of Curator (and therefore a single cron job in many cases!) to do multiple operations, in the listed order.

Ignoring the formatting of the file (assumed YAML for no real reason), you might have:

```bash
$ curator file --path curator.yml
```

Where the file might be (only showing delay to show other parameters at the same levels):

```
optimize:
  delay: 5
  indices:
    prefix: logstash
    older-than: 1
    newer-than: 2
bloom:
  indices:
    prefix: logstash
    older-than: 1
    newer-than: 2
```
