### ISSUE TITLE
Delete oldest indices to respect a volume threshold while ensuring a minimum history

### ISSUE THREAD

**Issue by Gueust** [elastic/curator#611]
I have a bunch of time range partitioned indexes (e.g.  logstash-2014.01.01) with a common prefix (e.g. 'logstash-' here)  and I want to delete the oldest indexes to respect a given volume threshold (e.g. 20Go).

I think that the feature exists using for instance:
```curator delete --disk-space 1024 indices <<index selection parameters>>```

In addition, I would like to be able to supply a time range (e.g. 1 months) preventing any deletion of indexes not older that that time range, even if the volume threshold is reached. The goal is to keep the volume under the threshold, while preventing any aggressive deletion of indexes if some unexpected peak of volume consumption by a given index.

If this feature interests you, I can contribute to add it. I am asking before coding it ^^ Any remarks ?

**Comment by untergeek** [comment]
This is already possible with Curator 4.0.  Here's an example configuration.  The `description` field explains what is going on.

You could try this configuration with the `--dry-run` flag first so nothing would actually get deleted.

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices.  Find which to delete by first limiting the list to logstash- 
      prefixed indices. Next filter by space, to those indices in excess of 
      20g of usage.  Then further filter those to prevent deletion of anything 
      less than 30 days old.
    options:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: space
      disk_space: 20
      reverse: True
      use_age: True
      source: creation_date
      timestring:
      field:
      stats_result:
    - filtertype: age
      source: creation_date
      direction: older
      timestring:
      unit: days
      unit_count: 30
```

**Comment by untergeek** [comment]
This feature will not be back ported or added to the 3.x branch, by the way.

**Comment by Gueust** [comment]
Great ! The example is not that simple and could be a very good example for the documentation (It helps me understand some options of the space filter, so it can helps others).

If I understood correctly, for the space filtertype, one could have also used:
```
- filtertype: space
      disk_space: 20
      reverse: 
      use_age: True
      source: name
      timestring: '%Y.%m.%d'
      field:
      stats_result:
```

Does the reverse:True also work ? (the descriptions states : "This means that if all index names share the same pattern with a date—e.g. index-2016.03.01—older indices will be selected first." However, I don't know if older indices are **selected** to compute the aggregated size of the indices first (in that case it will not be selected by the filter), or are **selected** first by the filter (meaning it will begin adding indices size on the opposite order). It it the second option for me (so the following should work).
```
- filtertype: space
      disk_space: 20
      reverse: True
      use_age: 
      source:
      timestring:
      field:
      stats_result:
```

The two last solutions could even be better ideas, if we consider that maybe some indices have been created at a different moment compated to what is stored in its name: maybe an old index containing corrupted data was deleted and created/filled again quite recently.
