### ISSUE TITLE
[Feature] Filter by count

### ISSUE THREAD

**Issue by untergeek** [elastic/curator#649]
This filter would keep only _n_ indices or snapshots.  It would be mandatory to sort by age somehow,  before running this, to ensure that desired indices or snapshots are not accidentally pruned.

**Comment by kdubezerra** [comment]
Is this feature going to be part of 4.1.0? If not, how can I achieve the same with, say, `curator version 4.0.6`?

**Comment by untergeek** [comment]
Funny you should ask.  I'm adding it right now.  Yes, it's slated for 4.1.0

**Comment by kdubezerra** [comment]
Sweet! I don't know if this is the right place to ask, but how would you use the filter-by-count feature to remove the N most recent indices?

**Comment by untergeek** [comment]
@kdubezerra 

So you want to remove not older, but newer indices?

Your config might look like this:

```
---
actions:
  1:
    action: delete_indices
    description: Delete the newest 10 indices by creation_date
    options:
      ignore_empty_list: True
      continue_if_exception: False
    filters:
    - filtertype: count
      count: 10
      reverse: False
      use_age: True
      source: creation_date
```

Please keep in mind that this is a _very_ simplistic configuration.  There are no other filters, so this will delete _any_ index recently created, including `.kibana` and the `.marvel-*` indices.  You should probably prepend the count filter with a pattern filter to select only indices matching a pattern.

Out of idle curiosity, why would you want to delete the _newest_ indices instead of older ones?  What's the use case?

**Comment by kdubezerra** [comment]
Thanks a lot for replying! I'll be using this feature as soon as the curator 4.1.0 gets to PyPI. And I'm sorry, my question was wrong, as I meant to ask how to remove **all but** the N most recent ones. I've updated the comment above to reflect what I really intended to ask. In that case, all I'd have to change from the code you posted would be setting `reverse` to `True`, correct? And you're right, I'dd also add a filter to get only indices that match a `"logstash-"` prefix. Thanks again!

**Comment by untergeek** [comment]
Ah, makes sense.  In that case, your config might look like this:

```
---
actions:
  1:
    action: delete_indices
    description: Delete all indices but the 10 most recent, by creation_date
    options:
      ignore_empty_list: True
      continue_if_exception: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: 'logstash-'
    - filtertype: count
      count: 10
      use_age: True
      source: creation_date
```

Note that `reverse` is omitted.  That's because the default is `True`, so it doesn't need to be there.  Also note the use of single quotes for the pattern filter `value`, `'logstash-'`.  This is because it's used as part of a regular expression.  It's best practices to single-quote anything in the value field.

**Comment by kdubezerra** [comment]
Hmmm thinking again, wouldn't that always delete only the 10 oldest indices? I think that matching everything that begins with 'logstash-' (thanks for the single vs. double quote heads up!), than excluding the 10 youngest ones would be what we want, no?

```
---
actions:
  1:
    action: delete_indices
    description: >-
      Delete all indices preffixed with "logstash-", except for the $count most
      recent ones. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: count
      count: 10
      reverse: False
      use_age: True
      source: creation_date
      exclude: True
```
