### ISSUE TITLE
Add configuration validation

### ISSUE THREAD

**Issue by hongyuan1306** [elastic/curator#674]
I am a new user to curator and with the latest version of curator (4.0.0) I started with the following action config:

```
actions:
  1:
    action: delete_indices
    fitlers:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: name
      timestring: '%Y.%m.%d'
      direction: older
      unit: days
      unit_count: 5
```

Instead of 'filters' i typed in 'fitlers', which is a fairly common error to make.

As a result, all my indices in elastics are removed. And it took me some time to figure out why this happened.

I would suggest that curator provide better protection against this sort of disaster. For example, when unrecognized options are encountered, an error shall be raised.

As in SQL, a statement like DELETE FROM table_name WHRER 1=1 shall not delete any thing.
