### ISSUE TITLE
CLI Snapshot action does not check for an empty IndexList

### ISSUE THREAD

**Issue by sherzberg** [elastic/curator#682]
I have been trying to run the snapshot action with this yml:

```yaml
actions:
  1:
    action: snapshot
    description: >-
      Snapshot logstash- prefixed indices older than 1 day (based on index
      creation_date) with the default snapshot name pattern of
      'curator-%Y%m%d%H%M%S'.  Wait for the snapshot to complete.  Do not skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: test_backup
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name:
      ignore_empty_list: True
      ignore_unavailable: True
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 1
      exclude:
```

But `ignore_empty_list` is not being honored. I tracked this down to a missing call to `self.index_list.empty_list_check()`. This diff addresses it.

```diff
diff --git a/curator/actions.py b/curator/actions.py
index 95ac3d0..b6ac5b9 100644
--- a/curator/actions.py
+++ b/curator/actions.py
@@ -727,6 +727,7 @@ class Snapshot(object):
         """
         Snapshot indices in `index_list.indices`, with options passed.
         """
+        self.index_list.empty_list_check()
         if not self.skip_repo_fs_check:
             test_repo_fs(self.client, self.repository)
         if snapshot_running(self.client):
```

I can send a PR but was looking for direction on how to test this. My first thought was to just create a similar integration test as the others in `test/integration/test_snapshot.py` and just create 0 indices.

Thoughts how how to add a test for this?
