### ISSUE TITLE
CLI: Not an IndexList Object

### ISSUE THREAD

**Issue by vidhyarti** [elastic/curator#703]
Trying to setup curator on my windows machine to create snapshots of elastic indices. I am following the steps mentioned in the latest documentation.
- Using curator 4.0.3
- Using 2.3.3 elasticsearch

Using the same configuration mentioned in the documentation but still getting this below error :

> 2016-07-25 22:37:20,073 ERROR     Failed to complete action: snapshot.  <class 'TypeError' at 0x000000001DC3C400>: Not an IndexList object. Type: <class 'curator.indexlist.IndexList' at 0x0000000002E609B8>.

Am i missing any thing ? or is this a known issue ?

My action file : 

```
Action yaml file :
actions:
  1:
    action: snapshot
    description: >-
      Snapshot logstash- prefixed indices older than 1 day (based on index
      creation_date) with the default snapshot name pattern of
      'curator-%Y%m%d%H%M%S'.  Wait for the snapshot to complete.  Do not skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: myrepo    
      name: shan
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:    
    - filtertype: age
      source: creation_date
      direction: younger      
      unit: days
      unit_count: 1
      field:
      stats_result:
      epoch:
      exclude:
```

**Comment by untergeek** [comment]
With this quoted text, I can't see if the YAML configuration indents are done properly.

It could be that your description says indices _older_ than one day but your filter block says _younger._

**Comment by untergeek** [comment]
Here's an example of one of my snapshot configurations:

```
  8:
    action: snapshot
    description: >-
      Snapshot daily indices older than 1 day (based on index
      creation_date) with the default snapshot name pattern of
      'daily-%Y%m%d%H%M%S'.  Wait for the snapshot to complete.  Do not skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      ignore_empty_list: True
      repository: Untergeek
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name: 'daily-%Y%m%d%H%M%S'
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override: 7200
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: timestring
      value: '%Y.%m.%d'
      exclude: False
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 1
      exclude:
    - filtertype: closed
```
