### ISSUE TITLE
Filter Element timestring can substring match incorrectly:  example %Y.%W matches %Y.%m%.d

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/curator#707]
During configuration of curator with multiple types of timestamped index names we encountered a case in which the timestring of %Y.%W would unexpectedly match an index with a %Y.%m.%d timestring.  Is it possible to add an anchor or option for an anchor to the timestring regex to more accurately match in these cases?

**Comment by untergeek** [comment]
The answer is just to employ another filter.  You can exclude a `pattern` `filtertype` with a `value` of `'%Y.%m.%d'`:

```
    - filtertype: pattern
      kind: timestring
      value: '%Y.%m.%d'
      exclude: True
```

This filter should work anywhere in the chain, but it might be easier to visualize if it appears _before_ the age filter with the weekly timestring.

**Comment by untergeek** [comment]
Since there's a simple fix for this, I'm going to mark it complete.  If you believe this is in error, please feel free to reopen this with a comment as to why, or open another ticket.

**Comment by jakommo** [comment]
I hit this today with the following config:

```
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%W'
      unit: weeks
      unit_count: 2
```

and adding an exclude filter solved it.

```
    filters:
    - filtertype: pattern
      kind: timestring
      value: '%Y.%m.%d'
      exclude: True
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%W'
      unit: weeks
      unit_count: 2
```

While there is a workaround, it sounds like a bug to me. `'%Y.%W'` should not match indices with `'%Y.%m.%d'`.
@untergeek are you open for discussion on this one? 

I'm curious to understand why this happens. Is `'%Y.%W'` translated to a regexp without an `$` at the end?
