### ISSUE TITLE
Suffix selection bug if value is not in single quotes

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/curator#726]
It seems that there is an index selection problem in curator 4. 

Suffixes that end in `0` don't match.      In the following example, `value: -2016.30` will not match, but  `value: -2016.33` will.    As a hack, you can match the index ending in a zero using a regex: `value: (.*-2016.3[0])`

**1) Put some indices in ES:**

```
PUT /test-2016.30
PUT /test-2016.33
```

**2) create a curator snapshot action** 

```
actions:
  1:
    action: snapshot
    description:  Testing Suffix Issue
    filters:
    - filtertype: pattern
      kind: suffix
      value: -2016.30
      exclude:
```

**3) Do it**

```
├ $ curator --config localhost-config.yml --dry-run snapshot-suffix0-problem.yml  | grep remains
< nothing found >
```
