### ISSUE TITLE
JSON / Logstash logging appears to be broken in Curator CLI

### ISSUE THREAD

**Issue by evanv** [elastic/curator#730]
When running `curator --config config.yaml --dry-run actions/reallocate.yaml`

from the command line with `config.yaml` containing 

```
client:
  hosts:
    - es-logs.myhost.com
  port: 9200
  use_ssl: True
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: True
  http_auth: myUser:myPass
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfomat: logstash
  logfile: /tmp/curator.json
  blacklist: ['elasticsearch', 'urllib3']
```

Curator is dropping default formatted logs, not json formatted logs. I've tried changing the logformat to JSON as well and it's still not outputting JSON

Is this user error on my end? Can anyone else get json logs from the CLI?
