### ISSUE TITLE
Add a "period" index filter type

### ISSUE THREAD

**Issue by DravenJohnson** [elastic/curator#733]
[Feature request]

Based on question: https://discuss.elastic.co/t/the-newest-curator-how-to-set-up-time-range-not-ages

> I need snapshot from (For example) July 1st to July 31st in early August; and (for example) Sept. 1st to Sept 30th in early October.
> 
> I cannot use age older/younger because all month are different (some month have 30 days and some have 31 days). The script will run in an automatic system which should work against all monthly snapshot. So changing config file will not work.
> 
> Furthermore, this will usually run around 2nd day of each month to take previous month's (1 to 30/31) indices snapshot (ONLY). But this script may sometime run on 5th or later due to various problem. So either age-day and age-month will not work based on our dry-run exam last week.

**Comment by untergeek** [comment]
My idea for this is:

```
- filtertype: period
  unit: [second|minute|hour|day|week|month|year]
  range_from: 1
  range_to: 1
  source: [name|creation_date|field_stats]
  timestring: 
  field:
  stats_value:
  exclude: False
```

This would get the entire period identified by `unit`, `unit_count` instances ago.  

For example, with `unit` set to `month`:

* A `range_from` and `range_to` of 0 would get the current month (even incomplete).
* A `range_from` and `range_to` of 1 would get the previous month (first through last day of month, however many days it might be)
* A `range_from` 1 and `range_to` of 2 would get the previous month and the month before that (first through last day of each month, however many days they might be)

One potential caveat is that all time values are in UTC, as this is how they're _all_ calculated in Curator right now, but that's also how all dates are stored in Elasticsearch, so that shouldn't be a big surprise.
