### ISSUE TITLE
Don't run with invalid syntax

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/curator#745]
Curator 4.0.6 will start and complete with invalid top level directives.  Additionally, no error logs are provided as evidence of invalid configuration.

This can provide a poor experience for new & experienced users.  E.g., the following will match & delete all indices, as `filter` (as opposed to the correct `filters`) is ignored.

```
actions:
  1
    action: delete_indices
    description: >-
      Blow stuff away
    options:
      continue_if_exception: False
      disable_action: False
    filter:
    - filtertype: pattern
      kind: prefix
      value: filebeat-
    - filtertype: age
      source: name
      timestring: '%Y-%m-%d'
      direction: older
      unit: days
      unit_count: 2
      exclude:
```
