### ISSUE TITLE
Close with delete aliases does not correctly close non alaised indices

### ISSUE THREAD

**Issue by evanv** [elastic/curator#764]
Suppose you have three indices 
1. foo
2. bar
3. baz

that match a Curator filter of some kind and are actionable under the close action.

Suppose as well you have one alias `bang` that points at indices `foo` and `bar`.

Suppose you perform a `close` action on these indices. Indices `foo` and `bar` will be closed; `baz` will not, because it doesn't have an alias.

This seems counter intuitive to me. It seems like Curator should delete an alias if it exists with this option, but continue with regularly scheduled programming if one does not.

**Comment by untergeek** [comment]
Are you using the `delete_aliases: True` [option](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_delete_aliases.html)?  That fixes this.

**Comment by evanv** [comment]
The unexpected behavior occurs when using delete aliases. sorry that wasn't clear. Let me be more concrete.

With /cat/indices output of
```
health status index                        pri rep docs.count docs.deleted store.size pri.store.size 
green  open   .marvel-es-1-2016.09.17        1   1   21591010        48656     19.9gb          9.9gb 
green  open   .kibana                        1   1         10            0    146.6kb         73.3kb 
green  open   .marvel-es-1-2016.09.19        1   1   27449391        46799     20.3gb         10.1gb 
green  open   .marvel-es-data-1              1   1       1509          116      1.4mb        350.2kb 
green  open   .marvel-es-1-2016.09.18        1   1   36045047        63832     26.4gb         13.1gb 
green  open   .marvel-es-1-2016.09.20        1   1   26587477       123860     19.9gb          9.9gb 
green  open   .marvel-es-1-2016.09.22        1   1   23443172        41974     16.6gb          8.3gb 
green  open   .marvel-es-1-2016.09.21        1   1   26336111        95626       21gb         11.9gb 
```

and /cat/aliases of
```
alias  index   filter routing.index routing.search 
kibana .kibana -      -             -                                  
```

and /tasks/marvel.yaml of

```
  1:
    action: close
    description: >-
      close indices
    options:
      continue_if_exception: True
      ignore_empty_list: True      
      delete_aliases: True
      timeout_override: 300
    filters:
      - filtertype: pattern
        kind: prefix
        value: .marvel-es-1
        exclude: False
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 2
        exclude: False 
  2:
    action: delete_indices
    description: >-
      delete indices
    options:
      continue_if_exception: True
      ignore_empty_list: True      
      timeout_override: 300
    filters:
      - filtertype: pattern
        kind: prefix
        value: .marvel-es-1
        exclude: False
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 5
        exclude: False
```

I would expect that several of these marvel indices are closed, despite the fact they have no aliases. Instead, they produce errors like:

```
{"@timestamp": "2016-09-22T11:49:14.759Z", "function": "log_request_fail", "linenum": 82, "loglevel": "WARNING", "message": "DELETE /.marvel-es-1-2016.09.17,.marvel-es-1-2016.09.18,.marvel-es-1-2016.09.19,.marvel-es-1-2016.09.20/_alias/_all [status:404 request:0.019s]", "name": "elasticsearch"}
{"@timestamp": "2016-09-22T11:49:14.760Z", "function": "cli", "linenum": 242, "loglevel": "ERROR", "message": "Failed to complete action: close.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: TransportError(404, u'aliases_not_found_exception', u'aliases [kibana] missing')", "name": "curator.cli"}
```

This is not problematic on this cluster. But it is a bit counterintuitive. Also, on clusters which have both aliased and non aliased indices (which we have in our other clusters), this forces you to write an additional close task that closes and does not remove aliases.
