### ISSUE TITLE
Getting <type 'exceptions.KeyError'>: 'count' when using count filter

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/curator#766]
[Count Filter](https://www.elastic.co/guide/en/elasticsearch/client/curator/4.1/filtertype_count.html) doesn't seem to be working as expected in Curator **4.1**, given this configuration:

```
actions:
  1:
    action: delete_snapshots
    description: >-
      Delete all snapshots other than latest 5 (based on name) for backup
      snapshots. 
    options:
      repository: 'my_backups'
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: 'curator-'
    - filtertype: count
      count: 5
      reverse: True
```

Results in:

```
2016-09-23 10:42:50,007 ERROR     Failed to complete action: delete_snapshots.  <type 'exceptions.KeyError'>: 'count'
```
