### ISSUE TITLE
No actionable items in list - error

### ISSUE THREAD

**Issue by serialdoom** [elastic/curator#784]
Im trying to set the replicas count for logstash and im getting this error:

```
curator --config curator.yml replicas.yml
2016-10-14 18:04:23,685 INFO      Action #1: replicas
2016-10-14 18:04:24,246 ERROR     Unable to complete action "replicas".  No actionable items in list: <class 'curator.exceptions.NoIndices'>
```

This is my curator.yml

```
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - 192.168.100.9
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```

and this is my replicas.yml that i think i copied as the [replicas example](https://github.com/elastic/curator/blob/master/examples/actions/replicas.yml)

```
actions:
  1:
    action: replicas
    description: >-
      Reduce the number of replicas to 5 for logstash-
    options:
      count: 0
      wait_for_completion: False
      timeout_override:
      continue_if_exception: False
      disable_action: false
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 5
      exclude:
```

There are definitely enough logstash indices to update with that script, but it keeps failing.
Is this a bug or a PEBKAC ?

edit:
tried with both versions:
```
curator, version 4.0.6
curator, version 4.1.2
```
