### ISSUE TITLE
Unable to delete close indices from action: delete_indices

### ISSUE THREAD

**Issue by umarmir** [elastic/curator#785]
Hi,

I am using action: `delete_indices` with `action: close` but getting error 
`curator  ~/.curator/deleteclose.yml                        
2016-10-19 06:34:33,400 INFO      Preparing Action ID: 1, "close"                 
2016-10-19 06:34:33,417 INFO      Trying Action ID: 1, "close": Close 7 days older indices via creation_date                                                        
2016-10-19 06:34:35,428 ERROR     Unable to complete action "close".  No actionable items in list: <class 'curator.exceptions.NoIndices'>   ` 
while when i checked there were many close indices but still it giving me this. If you plz guide me.

```
actions:
  1:
    action: close
    description: Close 7 days older indices via creation_date
    options:
      delete_aliases: True
      ignore_empty_list: False
      timeout_override: 300
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: regex
      value: .+-.+-.+-
      exclude:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 7
      exclude:
  2:
    action: delete_indices
    description: Delete 10 days older indices via creation_date
    options:
      ignore_empty_list: False
      timeout_override: 300
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: regex
      value: .+-.+-.+-
      exclude:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 10
      exclude:
```

```
curator --version                                          
curator, version 4.1.2   
```
