### ISSUE TITLE
Curator Beginner Here

### ISSUE THREAD

**Issue by elJoeyJojo** [elastic/curator#804]
Hello,

Just installed Curator 4.1.2 on my Ubuntu 15.10 ElasticSearch/Kibana Server. 
Just a little confused on how to set this up and the ElasticSearch guide is not very clear on what it is I need to do in order to setup Curator to simply remove Indices 60 days or older.  I mean I see here: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/ex_delete_indices.html 

But this really doesn't tell me how to set it up? I simply installed it via the APT Repository and from there doesn't really say where to get an "action file" and the "configuration file" and I checked the home folder and /opt/elasticsearch-curator but no sign of those files. . Is this something I need to write myself? All I need to do really is delete indices on my ElasticSearch Server for 60 days and older (pretty simple no?) I can see all my dashboards on Kibana just fine but running out of space quite quickly.

Sorry this is very intro and I apologize if this is technically not an issue but I really didn't know where else to go.

Thanks

**Comment by untergeek** [comment]
Yes.  You are supposed to create your own yaml files.  

The configuration file can be in `~/.curator/curator.yml`, in which case you don't have to specify it on the command line.  The example for this file is at https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html.  You could cut/paste the example file right there at the top and change the values to your own, e.g.

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - 127.0.0.1
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```
Change `127.0.0.1` to be the IP of your Elasticsearch client node.

As for the _action.yml_ file, you can use the example at the URL you provided, https://www.elastic.co/guide/en/elasticsearch/client/curator/current/ex_delete_indices.html and edit as needed:
```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 45 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 45
      exclude:
```
This bare example would need `disable_action: False`, or it will ignore the action (this is a safety feature so users copying the example won't accidentally do something they do not intend).  This action will purge all indices starting with `logstash-` and older than 45 based on the date in the index name.  If you have `logstash-` prefixed indices, you could leave this as-is, otherwise replace `logstash-` with the prefix of your choice, and `unit_count: 45` should perhaps be changed to `unit_count: 60` for 60 days.

Save this file to whatever name and path you want, e.g. `/path/to/my_action.yml`.  You would then call:
```
$ curator --dry-run /path/to/my_action.yml
```
And make sure the indices set to be deleted are _exactly_ what you expect, and no others.  You may need to add or tweak the filters for your delete action a bit.  Once you're satisfied, re-run the above command, omitting the `--dry-run` portion to actually execute the action.
