### ISSUE TITLE
filtertype: last update age

### ISSUE THREAD

**Issue by gfrankliu** [elastic/curator#811]
Is it possible to delete indices that haven't been written to for X number of days?
I assume the filtertype "age" is only for the index creation time, not the last update time.

**Comment by untergeek** [comment]
Have you looked at using `source: field_stats` (see [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_source.html#_field_stats)) with the age filter?  So long as you are looking for a timestamp field, this may do what you want.

Otherwise, the filter you describe would require a query, as that data does not appear in the cluster state metadata. Here's a sample of the data in the `'settings'` key:
```
{u'index': {u'number_of_replicas': u'1', u'uuid': u'GV0wgrQSSrOrcGo5kGTGNg', u'number_of_shards': u'3', u'creation_date': u'1472688005429', u'version': {u'upgraded': u'5000099', u'created': u'2030399'}, u'refresh_interval': u'5s'}}
```

This is where `creation_date` comes from, as well as the number of shards and replicas.  There is no "last touched" date in here, unfortunately.  If you wanted to write an extra filter that does queries, I suppose it could be merged.  It's not something that's on my radar, though.

**Comment by gfrankliu** [comment]
field_stats with \@timestamp seems like a solution.
If I want to set a filter to delete all indices whose last timestamp is more than 30 days, shall I do:

```
    - filtertype: age
      source: field_stats
      field: @timestamp
      stats_result: max_value
      direction: older
      unit: days
      unit_count: 30
      exclude:
```
