### ISSUE TITLE
Improve documentations on age/timestring behavior.

### ISSUE THREAD

**Issue by jakommo** [elastic/curator#859]
I hit an issue today, where an monthly index would have been deleted while it was not clear for what reason.

Config:
```
action: delete_indices 
description: "Delete indices older than 3 months"
options: 
  ignore_empty_list: True 
filters: 
  - filtertype: age 
    source: name 
    direction: older 
    timestring: '%Y.%m' 
    unit: months 
    unit_count: 3 
  - filtertype: pattern 
    kind: prefix 
    value: data- 
    exclude: False 
```

With DEBUG, resulting in:

```
2016-12-30 09:17:44,494 DEBUG          curator.indexlist           __actionable:35   Index data-2016.10 is actionable and remains in the list.
2016-12-30 09:17:44,494 DEBUG          curator.indexlist            __excludify:58   Remains in actionable list: Index "data-2016.10" age (1475280000), direction: "older", point of reference, (1475313464)
```

After digging into it, I discovered that this is due to "month" being calculated as `30*86400`, which is documented [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_unit.html) and makes it clear that this was caused by:
Now (`1483089464`) minus `3*86400`. E.g. `1483089464 - 7776000 = 1475313464` (UTC: Saturday 1st October 2016 09:17:44 AM), but the reference date of the index was 1475280000 (UTC: Saturday 1st October 2016 00:00:00 AM) and thus "older".

Using this calculation it was correct to delete the index, but I think configuring:
```
    timestring: '%Y.%m' 
    unit: months 
    unit_count: 3 
```

gives the wrong expectation that that running this in 2016.12 would not delete 2016.10, even if it's run on 2016.12.31.

As a workaround I used the following config, making use of the field_stats and the actual date of the documents in the index, rather than the index name. 

```
action: delete_indices 
description: "Delete indices older than 3 months" 
options: 
  ignore_empty_list: True 
filters: 
  - filtertype: age 
    source: field_stats
    field: '@timestamp'
    stats_result: max_value
    direction: older 
    unit: months 
    unit_count: 3 
  - filtertype: pattern 
    kind: prefix 
    value: data- 
    exclude: False 
```

I think a note on the [filtertype age page](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_age.html), explaining that this might behave diffrently when using monthly indices, could be helpful to users.
