### ISSUE TITLE
Weekly index 2017_1

### ISSUE THREAD

**Issue by sundarv85** [elastic/curator#860]
Hello,

I use curator 4.0.5 and have the following actions file

```
actions:
  1:
    action: alias
    description: >-
      I can make the description span multiple
      lines by putting ">-" at the beginning of the line,
      as seen above.  Subsequent lines must also be indented.
    options:
      name: data_last_3_months
      extra_settings:
      timeout_override:
      continue_if_exception: False
      disable_action: False
    add:
      filters:
        - filtertype: pattern
          kind: prefix
          value: data_
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y_%W'
          unit: weeks
          unit_count: -1
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y_%W'
          unit: weeks
          unit_count: 12
          exclude: True
```

We already have indices `data_2016_52` and `data_2017_1`. However, as of today `data_2017_1` is not added into the alias `data_last_3_month`, even though today is already 2017. Our index is created based on `ISO 8601` ISO week.

What am I missing here. This year Jan 1st is on Sunday. But I'm running this on Jan 2nd, so the ISO week should not have an issue.
