### ISSUE TITLE
Curator deletes index patterns and saved searches 

### ISSUE THREAD

**Issue by alexisCata** [elastic/curator#866]
I'm using curator to delete elastic search indexes. When I executed it, it deletes also index patterns and saved searches. How I can avoid this behavior? I only want to delete the data, not the index patterns and the saved searches

`curator --config /root/curator/CONFIG.YML /root/curator/ACTION_FILE.YML`

CONFIG.XML
```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - vps222682.ovh.net
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```
ACTION_FILE.YML 
```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 10 days (based on index creation_date). 
      Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 20
      exclude:
```

**Comment by untergeek** [comment]
Have you tried using the `--dry-run` flag? It's a great way to see what's going to be acted on before you do it for real. 

If you're only filtering by `creation_date`, it will find _all_ of your indices that age. The `timestring` is ignored in such a case. 

You could use the `kibana` filter type, but you would need to set `exclude: True` to _exclude_ the Kibana indices.

**Comment by alexisCata** [comment]
I found the solution with the filterype: kibana and exclude: True
Now is working! 
But anyways @untergeek many thanks for your help

ACTION_FILE.YML
```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 20 days (based on index creation_date). 
      Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 20
      exclude:
    - filtertype: kibana
      exclude: True
```
