### ISSUE TITLE
empty list in add or remove filter causes alias action to fail

### ISSUE THREAD

**Issue by jakommo** [elastic/curator#883]
Already discussed this internally with @untergeek , opening it up for a public discussion.

Creating an action to add and remove indices to an alias (e.g. last 7 days), is an atomic operation and fails if one of the filers receives an empty list. I.e. if this action is run, while the cluster only has indices for the last 5 days, the `remove` filter would fail, causing the whole action to fail.  

Also reported via: https://discuss.elastic.co/t/curator-alias-add-not-working-if-remove-list-is-empty/73549

Example config:
```
actions:
        last-7-days: 
                action: alias 
                description: "Add / remove indexes from last-7-days alias"
                options: 
                        name: last-7-days 
                        ignore_empty_list: True 
                add: 
                        filters: 
                                - filtertype: pattern 
                                  kind: prefix 
                                  value: logstash- 
                                - filtertype: age 
                                  direction: younger 
                                  source: name 
                                  timestring: '%Y.%m.%d' 
                                  unit_count: 7 
                                  unit: days 
                remove: 
                        filters: 
                                - filtertype: pattern 
                                  kind: prefix 
                                  value: losgstash- 
                                - filtertype: age 
                                  direction: older 
                                  source: name 
                                  timestring: '%Y.%m.%d' 
                                  unit_count: 7 
                                  unit: days
``` 

On one side I feel this behavior is correct, the action instructs curator to do these two steps and since one is failing, the whole actions fails. Just continuing with one filter failed, could lead to unexpected behavior. E.g. if filters or the whole action depend on each other. 
But in case of the alias I can understand that user exception is to just add the indices and skip the remove part until there are indices in the cluster that can be removed from the index. 

Just continuing with a failed filter doesn't sound like a good approach either, even in case of aliases.
Imagine relaying on a query that uses a last 7 days alias, if the remove "silently" fails, it could lead to this alias returning results for the last 3 weeks instead, resulting in wrong data.

Purposing to make this a configurable option for the user (to be "ok" with failing a specific or any part of the action).
