### ISSUE TITLE
Can we do a snapshot of the kibana index?

### ISSUE THREAD

**Issue by cinhtau** [elastic/curator#884]
Hi, I try to use curator 4.2.5 for snapshot the `.kibana` index, which IMHO is very important, since it contains all the visuals and dashboards. Previously we use Sense or a shell script with curl. 

To be more specific. I want **only** the `.kibana` index in my snapshot.

I tried
```yaml
---
actions:
  1:
    action: snapshot
    description: >-
      Snapshot kibana to nas
    options:
      repository: six-nas
      name: 'kibana-%Y%m%d'
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: .kibana
      exclude: False
```

In Debug the .kibana index is not listed and thus no snapshot is done. Is it possible?

**Comment by corey-hammerton** [comment]
Try using the [kibana filter](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_kibana.html) instead of a pattern filter.

**Comment by cinhtau** [comment]
Yes tried that too with opposite of exclude. Not working.

**Comment by untergeek** [comment]
Apologies, but the Kibana filter is exclude-only, since it filters multiple kinds of indices.  You can tell it `exclude: False`, but it won't do any different:

```
        for index in self.working_list():
            if index in [
                    '.kibana', '.marvel-kibana', 'kibana-int', '.marvel-es-data'
                ]:
                self.__excludify(True, exclude, index)
```

It is a hold-over from Curator 3.  It's exclusively there to prevent you from accidentally deleting `.kibana` indices.  I should probably document this functionality better.

That said, what you want to do can be achieved like this:

```
actions:
  1:
    action: snapshot
    description: Backup the .kibana index
    options:
      ignore_empty_list: True
      repository: YOUR_REPO_NAME
      name: 'kibana-%Y%m%d%H%M%S'
    filters:
    - filtertype: pattern
      kind: regex
      value: '^\.kibana$'
```

You could also keep the `prefix` filtertype you're using now, but you need to escape the `.`, as all of the pattern types are actually part of regular expressions:

This works:
```
    prefix: '\.kibana'
```

It also works with `curator_cli`, but you have to escape the back-slash (rather than the period) in order for it to appear in the resulting JSON:

BAD:
```
$ curator_cli show_indices --filter_list '{"filtertype":"pattern", "kind":"prefix", "value":"\.kibana"}'
Usage: curator_cli show_indices [OPTIONS]

Error: Invalid value for "--filter_list": Invalid JSON: {"filtertype":"pattern", "kind":"prefix", "value":"\.kibana"}
```

GOOD:
```
$ curator_cli show_indices --filter_list '{"filtertype":"pattern", "kind":"prefix", "value":"\\.kibana"}'
.kibana
```
