### ISSUE TITLE
Curator skipping actions even if continue in exception

### ISSUE THREAD

**Issue by gitime** [elastic/curator#901]
Hi,

I am using Curator version 4.1.0. I have the action file like below;

```
actions:
  1:
    action: snapshot
    description: >-
      Archiving indices older then 10 days
    options:
      repository: myesbackup
      name: backupa-%Y%m%d%H%M%S
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: mylogsa-
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y-%m-%d'
      unit: days
      unit_count: 10
  2:
    action: snapshot
    description: >-
      Archiving indices older then 10 days
    options:
      repository: myesbackup
      name: backupb-%Y%m%d%H%M%S
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: mylogsb-
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y-%m-%d'
      unit: days
      unit_count: 10
  3:
    action: snapshot
    description: >-
      Archiving indices older then 10 days
    options:
      repository: myesbackup
      name: backupc-%Y%m%d%H%M%S
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: mylogsc-
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y-%m-%d'
      unit: days
      unit_count: 10
```

Only  `mylogsc` is present in my elasticsearch, and it's snapshot is defined last. But, since my actions 1 fails, it is not proceeding to other actions (here only action 3 has real index). I am getting the below trace.

```
2017-03-03 08:23:21,296 INFO      Preparing Action ID: 1, "snapshot"
2017-03-03 08:23:21,300 INFO      Trying Action ID: 1, "snapshot": Archiving indices older then 10 days
2017-03-03 08:23:21,355 ERROR     Unable to complete action "snapshot".  No actionable items in list: <class 'curator.exceptions.NoIndices'>
```

Why is this happening and how can I fix this?

Thanks in advance.
