### ISSUE TITLE
"<class 'KeyError'>: 'settings'" with curator 4 when run on AWS Elastic 5.1

### ISSUE THREAD

**Issue by jackiekhuu-work** [elastic/curator#915]
I'm trying to use curator to clean up indices in AWS Elasticsearch version 5.1.
For accessing to AWS Elastic, I used this npm package [aws-es-kibana](https://www.npmjs.com/package/aws-es-kibana) to create a proxy on localhost:9200.
Here are my configurations:
```
$ curator --version
curator, version 4.2.6
```
```
$ curl localhost:9200
{
  "name" : "kWYfz2u",
  "cluster_name" : "011019559463:search",
  "cluster_uuid" : "DIMYcQvhQSaELphXp_zdXg",
  "version" : {
    "number" : "5.1.1",
    "build_hash" : "5395e21",
    "build_date" : "2016-12-15T22:47:19.049Z",
    "build_snapshot" : false,
    "lucene_version" : "6.3.0"
  },
  "tagline" : "You Know, for Search"
}
```
config.yml
```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - 127.0.0.1
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False
```

actions.yml
```
actions:
  1:
    action: close
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7
```

when I run it, I receive the error:
```
$curator --config config.yml action.yml
2017-03-31 09:58:02,754 INFO      Preparing Action ID: 1, "close"
2017-03-31 09:58:02,860 INFO      Trying Action ID: 1, "close": No description given
2017-03-31 09:58:03,535 ERROR     Failed to complete action: close.  <class 'KeyError'>: 'settings'
```

What is this kind of error, is it because I tried to use curator with AWS Elasticsearch?
