### ISSUE TITLE
Index not found exception after reindex operation to alias

### ISSUE THREAD

**Issue by chfrst** [elastic/curator#941]
If I'm trying to reindex some indices to an alias like this:
```
---
actions:
  1:
    action: reindex
    options:
      ignore_empty_list: True
      continue_if_exception: False
      disable_action: False
      wait_interval: 9
      max_wait: -1
      request_body:
        source:
          index: test-2017.04.24
        dest:
          index: per-week-test
    filters:
    - filtertype: none
```
I get an Index not found exception:
```
2017-04-25 11:44:44,373 ERROR     curator.actions.reindex              do_action:1145 Index "per-week-test" not found after reindex operation. Check Elasticsearch logs for more information.
```
per-week-test is an alias for index test-weekly-000001 which gets filled during the action. It seems like the verification after the reindex-operation doesn't work with aliases.
