### ISSUE TITLE
Exclude should only be True when explicitely set to True

### ISSUE THREAD

**Issue by patrick-vonsteht** [elastic/curator#945]
In a curator action file you can set `exclude: True` on a filter to negate its effect. As setting this accidentally can destroy much data, this setting should only accept "True" or "False" or empty (meaning the default: False). However, adding a yaml list below exclude is also interpreted as True.

Here is an example:

Intended configuration that works as expected, removing all indices starting with test, older than 14 days:

```yaml
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 14 days
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: test
        exclude:
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 14
```

Accidentally wrongly indented configuration that deletes all indices except those starting with test:

```yaml
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 14 days
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: test
        exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 14
```

Tested on:
Curator Version: 4.2.6
Elasticsearch Version: 5.2.2
