### ISSUE TITLE
restore is stuck and never exit even when status is "DONE"

### ISSUE THREAD

**Issue by Strijd** [elastic/curator#966]
New bug related to #962 
restore is stuck and never exit even when status is "DONE"
```
Index "index_v0.2_2017-02-12_536a9247f9fa4fc7a7942ad46ea14e0d" is still in stage "DONE
```
```
actions:
  1:
    action: restore
    description: restore via curator
    options:
      repository: force-merge
      name: force-merge
      extra_settings:
        settings:
          number_of_shards: 1
          number_of_replicas: 0
      wait_for_completion: True
      include_aliases: True
      max_wait: 3600
      wait_interval: 10
      ignore_unavailable: False
      include_global_state: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: force-
```

more info:
The restore is done via a single elasticsearch  node with ```node.master: true```. 
index size: 24G
curator: 5.0.3
