### ISSUE TITLE
Additional option for reindex action

### ISSUE THREAD

**Issue by kobybr** [elastic/curator#975]
Add option to delete the source index upon successful completion of the reindex action

**Comment by untergeek** [comment]
That's already possible.

It's remarkably simple to duplicate the filters that selected the source index (provided you did that) in the very next action and delete the index or indices you selected.

```
---
actions:
  1: 
    action: reindex
    options:
      continue_if_exception: False
      wait_interval: 9
      max_wait: -1
      request_body:
        source:
          index: REINDEX_SELECTION
        dest:
          index: logs-2017.04   
    filters:
    - filtertype: pattern
      kind: prefix
      value: logs-
    - filtertype: period
      source: creation_date
      range_from: -1
      range_to: -1
      unit: months
  2:
    action: delete_indices
    options:
      continue_if_exception: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logs-
    - filtertype: period
      source: creation_date
      range_from: -1
      range_to: -1
      unit: months
```

 With `continue_if_exception` set to `False` (which is the default), it will not continue and delete anything unless the reindex is successful.
